import json,time
from pathlib import Path
from playwright.sync_api import sync_playwright
out=Path('/workspace/prisma-root-export-fix');f=json.loads((out/'user-preset.json').read_text());events=[];errors=[]
def event(item):
 events.append(item);print(json.dumps(item),flush=True);(out/'cancel-ui-events.json').write_text(json.dumps(events,indent=2))
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox','--use-angle=gl-egl','--ignore-gpu-blocklist','--disable-gpu-sandbox']);page=b.new_page(viewport={'width':1440,'height':1000},accept_downloads=True);page.set_default_timeout(120000);page.on('pageerror',lambda e:errors.append(str(e)))
 def app_route(route):
  route.fulfill(content_type='application/javascript',body=Path('/workspace/prisma-studio/dist/app.js').read_text()+'\nwindow.qaCancel=()=>({state:structuredClone(state),busy,cancelled,width:exportRenderer?.canvas.width,height:exportRenderer?.canvas.height,pending:!!exportRenderer?.completionSync,lost:exportRenderer?.gl.isContextLost(),programs:exportRenderer?[...exportRenderer.programs.keys()]:[]});window.qaIdentity=()=>exportRenderer;')
 page.route('**/app.js*',app_route);page.add_init_script('localStorage.setItem("prisma-preview-quality","fluid");localStorage.setItem("prisma-current-v2",'+json.dumps(json.dumps({'state':f['state'],'ratio':f['ratio'],'phase':f['phase']}))+')');page.goto('http://127.0.0.1:4186/',wait_until='domcontentloaded');page.wait_for_function('window.prismaReady && window.qaCancel');initial=page.evaluate('window.qaCancel().state');page.locator('#export-open').click();page.locator('#export-width').fill('128');page.locator('#export-height').fill('72');page.locator('#export-height').dispatch_event('change');page.locator('#download').click();event({'stage':'render-start'})
 page.wait_for_function('parseFloat(document.querySelector("#progress-fill").style.width)>0 && window.qaCancel().busy');percent=page.locator('#progress-fill').get_attribute('style');page.evaluate('window.cancelledRenderer=window.qaIdentity()');start=time.monotonic();page.locator('#export-cancel').click();page.wait_for_function('!window.qaCancel().busy',timeout=30000);s=page.evaluate('window.qaCancel()');assert s['state']==initial and not s['pending'] and not s['lost'] and s['width']==1 and s['height']==1,s;event({'stage':'cancelled','atProgress':percent,'seconds':time.monotonic()-start,'message':page.locator('#export-message').inner_text(),'programs':s['programs']})
 with page.expect_download(timeout=120000) as info:page.locator('#download').click()
 info.value.save_as(out/'user-roots-cancel-retry.png');page.wait_for_function('!window.qaCancel().busy');s=page.evaluate('window.qaCancel()');assert s['state']==initial and not s['pending'] and not s['lost'];assert page.evaluate('window.cancelledRenderer===window.qaIdentity()');assert (out/'user-roots-cancel-retry.png').read_bytes()==(out/'user-roots-128.png').read_bytes();assert not errors,errors;event({'stage':'PNG_CANCEL_RETRY_PASS','errors':errors,'samePixelsAndFileAsUncancelled':True})
 page.locator('#export-close').click();page.locator('#creation-description').fill('rendilo morbido nel movimento, durata 2, velocità 2');page.locator('#description-apply').click();page.locator('#play').click();page.locator('#export-open').click();page.locator('[data-export="video"]').click();page.locator('#export-width').fill('64');page.locator('#export-height').fill('64');page.locator('#export-height').dispatch_event('change');page.locator('#video-fps').select_option('60');downloads=[];page.on('download',lambda d:downloads.append(d));page.locator('#download').click();start=time.monotonic();last=0
 while not downloads and time.monotonic()-start<600:
  page.wait_for_timeout(100)
  if time.monotonic()-start-last>5:
   last=time.monotonic()-start;s=page.evaluate('window.qaCancel()');event({'stage':'video-progress','seconds':last,'text':page.locator('#progress-text').inner_text(),'message':page.locator('#export-message').inner_text(),'busy':s['busy'],'lost':s['lost']})
   if not s['busy'] and not downloads:raise AssertionError('Video stopped without download: '+page.locator('#export-message').inner_text())
 assert downloads,'Video did not complete within600seconds'
 downloads[0].save_as(out/'user-roots-gentle-64-60fps.mp4');page.wait_for_function('!window.qaCancel().busy');s=page.evaluate('window.qaCancel()');assert not s['pending'] and not s['lost'] and s['width']==1 and s['height']==1;assert page.evaluate('window.cancelledRenderer===window.qaIdentity()');assert s['state']['duration']==2 and s['state']['speed']==2;event({'stage':'VIDEO_PASS','seconds':time.monotonic()-start,'bytes':(out/'user-roots-gentle-64-60fps.mp4').stat().st_size,'errors':errors});assert not errors,errors;b.close()

