// Short explanations shared by hover, keyboard focus and touch.
const HELP={
 volume:'Regola la profondità della figura. A 1 le proporzioni non vengono schiacciate.',
 stretchX:'Allarga o comprime la forma in orizzontale.',stretchY:'Allunga o comprime la forma in verticale.',stretchZ:'Allunga o comprime la forma in profondità.',
 scale:'Ingrandisce tutta la figura nella tavola, senza cambiare il formato del video.',positionX:'Sposta la figura a destra o a sinistra.',positionY:'Sposta la figura in alto o in basso.',
 rotateX:'Inclina la figura avanti e indietro.',rotateY:'Ruota la figura lateralmente.',rotateZ:'Ruota la figura sul piano dell’immagine.',
 deform:'Deforma la superficie con pieghe ampie. A 0 conserva la geometria di base.',asymmetry:'Sbilancia la sagoma tra i due lati.',twist:'Avvolge la forma attorno al suo asse verticale; il segno inverte il verso.',
 waves:'Aggiunge increspature sulla forma. La loro frequenza si regola separatamente.',waveScale:'Aumentando il valore le increspature diventano più fitte.',
 roundness:'A 0 la base è sferica; aumentando si avvicina a un cubo con angoli morbidi.',taper:'Assottiglia una delle estremità; il segno cambia il lato.',bendX:'Piega la figura lateralmente.',bendY:'Piega la figura in verticale.',pinch:'Stringe la parte centrale della forma.',
 hole:'Apre un foro attraverso la forma. A 0 il foro scompare.',holeX:'Sposta il foro orizzontalmente.',holeY:'Sposta il foro verticalmente.',holeShape:'Trasforma il contorno del foro da circolare a squadrato.',holeAspect:'Allarga o stringe il foro senza spostarlo.',rimRound:'Ammorbidisce l’incontro tra superficie e ritagli.',cut:'Sottrae una porzione di forma; a 0 elimina il ritaglio.',cutX:'Sposta il ritaglio lateralmente.',cutY:'Sposta il ritaglio verticalmente.',cutAspect:'Cambia le proporzioni del ritaglio.',edge:'Sfuma il bordo esterno della figura.',lobeAmount:'Fa emergere lobi dalla superficie.',lobes:'Numero dei lobi; visibile quando Petali e lobi è sopra 0.',
 metal:'Passa da materia diffusa a metallo: i riflessi prendono il colore della palette. Non aggiunge una tinta fucsia.',roughness:'Allarga e ammorbidisce i riflessi. A 0 sono più nitidi, a 1 più diffusi.',gloss:'Regola l’intensità dei riflessi delle luci e dell’ambiente.',iridescence:'Aggiunge variazioni cromatiche ai riflessi secondo l’angolo di luce e vista. La palette resta il colore di base.',
 emission:'Luce prodotta dalla materia stessa. Se alta, rende meno visibili le ombre delle luci.',transparency:'Riduce la parte opaca della materia. Nelle particelle i riflessi restano visibili; l’opacità dei granelli si regola in Granelli.',
 refraction:'Indice ottico: cambia quanto la materia trasparente devia la luce.',thickness:'Aumenta il percorso ottico dentro la materia.',fullness:'Da pellicola sottile a oggetto pieno: regola insieme guscio e spessore.',hollow:'Svuota l’interno lasciando una parete.',wallThickness:'Spessore della parete, quando la forma è cava.',thinShellMode:'Attiva un guscio sottile con poca distorsione dello sfondo.',
 thinFilm:'Intensità della pellicola che produce riflessi iridescenti.',filmThickness:'Spessore ottico in nanometri: cambia i colori di interferenza della pellicola.',iridShift:'Sposta le tinte del riflesso iridescente senza cambiare la palette.',iridScale:'Cambia la variazione cromatica dell’iridescenza sulla superficie.',
 coat:'Aggiunge uno strato di vernice trasparente sopra la materia.',coatRoughness:'Sfoca i riflessi dello strato di vernice.',fresnel:'Aumenta i riflessi visti di taglio, lungo i bordi.',dispersion:'Separa leggermente i colori nelle rifrazioni.',absorption:'Assorbe più luce lungo i percorsi dentro la materia.',tintStrength:'Intensità del colore interno nelle parti trasparenti.',internalColor:'Tinta della luce che attraversa la materia.',
 translucency:'Lascia filtrare la luce dal lato opposto della superficie.',scattering:'Diffonde la luce dentro la materia, rendendola più lattiginosa.',scatterDirection:'Orienta la diffusione interna in avanti o all’indietro.',subsurface:'Aumenta la luce diffusa sotto la superficie.',sssRadius:'Distanza percorsa dalla luce sotto la superficie.',sssColor:'Colore della diffusione sotto la superficie.',anisotropy:'Allunga i riflessi come su una superficie satinata.',anisotropyAngle:'Ruota la direzione dei riflessi allungati.',surfaceTexture:'Aggiunge irregolarità molto fini alla superficie.',
 textureDepth:'Intensità del rilievo. A 0 la superficie è liscia.',textureScale:'Aumentando, la texture diventa più fitta e fine.',textureOrganic:'Rende meno regolare la distribuzione della texture.',textureAngle:'Ruota la direzione della texture.',textureWrinkles:'Quantità di grinze sottili.',textureFolds:'Quantità di pieghe ampie.',textureWear:'Quantità di abrasioni irregolari.',textureRipples:'Quantità di increspature ripetute.',
 petalAmount:'Mescola la sfera di base con petali, punte e appendici.',petalGrowth:'Fa emergere le appendici dalla superficie: 0 rientrate, 1 sviluppate.',petalCount:'Numero di appendici in ogni corona.',petalOpen:'Apre i petali verso l’esterno.',petalCurl:'Curva le estremità verso l’interno o l’esterno.',petalLength:'Allunga le appendici.',petalWidth:'Larghezza delle appendici.',petalInflate:'Gonfia il corpo dei petali.',petalSharp:'Assottiglia le estremità fino a punte acute.',petalCoverage:'Da una sola corona a distribuzione su tutta la sfera.',petalRows:'Numero di file di appendici sulla sfera.',petalPhase:'Ruota la disposizione delle appendici.',petalBlend:'Ammorbidisce il raccordo tra appendici e sfera.',petalRoot:'Allarga la base di innesto delle appendici.',petalRandom:'Rende irregolare la lunghezza delle appendici.',petalWander:'Rende sinuoso il percorso delle appendici.',petalCoil:'Avvolge le appendici attorno alla sfera; il segno cambia verso.',petalReentry:'Curva le estremità per farle rientrare nella sfera.',petalKnots:'Aggiunge rigonfiamenti alle appendici.',petalRidges:'Aggiunge nervature lungo le appendici.',petalDisorder:'Sfalsa la disposizione regolare delle appendici.',stemAmount:'Fa crescere un gambo opzionale.',stemRadius:'Regola lo spessore del gambo.',stemBend:'Piega il gambo.',
 gradientAngle:'Ruota la direzione in cui i colori attraversano la materia.',gradientScale:'Cambia quante volte il gradiente attraversa la figura.',gradientOffset:'Fa scorrere i colori lungo il gradiente.',colorSoftness:'Da bande di colore nette a transizioni morbide.',colorWaveAmount:'Deforma la distribuzione dei colori in onde.',colorWaveBands:'Numero delle fasce cromatiche; richiede Onde di colore sopra 0.',colorWavePhase:'Sposta le onde cromatiche lungo il loro ciclo.',colorWaveHeight:'Distribuisce le onde cromatiche lungo l’altezza.',colorWaveRadius:'Distribuisce le onde cromatiche dal centro all’esterno.',colorWaveSwirl:'Avvolge i colori in un vortice.',colorWaveWarp:'Rende ondulati i confini delle fasce cromatiche.',glow:'Diffonde un alone attorno alle zone luminose. Un valore alto può nascondere dettagli e colori.',
 environmentPower:'Intensità delle luci diffuse e dei riflessi dell’ambiente.',environmentAngle:'Ruota l’ambiente attorno alla figura, spostando i riflessi.',environmentRefraction:'Quanto l’ambiente è visibile attraverso le rifrazioni.',environmentRotate:'Fa ruotare l’ambiente nel loop.',environmentCycles:'Numero di giri dell’ambiente in un loop.',filmFlow:'Fa scorrere i colori della pellicola nel tempo.',filmSwirl:'Anima i vortici della pellicola.',filmCycles:'Ripetizioni del movimento della pellicola in un loop.',
 duration:'Durata di base del loop. La durata esportata è questo valore diviso Velocità globale.',speed:'Accelera o rallenta l’intero loop. A 0,5 la durata raddoppia.',motion:'Moltiplica l’ampiezza delle oscillazioni attive. Non modifica i giri continui.',perfectLoop:'Fa completare cicli interi a forma, luci e colori per raccordare inizio e fine.',animateRotation:'Attiva una rotazione completa della figura.',animateShape:'Attiva oscillazioni di forma e volume.',animateColor:'Fa scorrere la palette nel tempo.',animateLight:'Attiva l’orbita delle luci.',
 exposure:'Aumenta o riduce la luce complessiva in stop fotografici.',brightness:'Schiarisce o scurisce l’immagine.',contrast:'Aumenta o riduce la separazione tra chiari e scuri.',saturation:'Intensità dei colori: 0 è bianco e nero, 1 conserva la saturazione.',temperature:'Sposta il bilanciamento tra luce calda e fredda.',photoTint:'Correzione verde / magenta. A 0 non aggiunge dominanti.',gamma:'Regola soprattutto i mezzitoni.',blacks:'Schiarisce o scurisce le zone in ombra.',highlights:'Recupera o enfatizza le alte luci.',vignette:'Scurisce gli angoli dell’immagine.',lensDistortion:'Incurva l’immagine come una lente.',grain:'Intensità della grana fotografica.',grainSize:'Dimensione dei granelli fotografici.',photoAll:'Applica la correzione fotografica anche allo sfondo.',
 background:'Colore principale dello sfondo.',background2:'Secondo colore del gradiente o fondale.',bgAngle:'Ruota il gradiente di sfondo.',bgHeight:'Sposta in alto o in basso la transizione del fondale.',bgSoftness:'Allarga e ammorbidisce la transizione del fondale.',bgWash:'Aggiunge una zona più luminosa al centro del fondale.',bgShade:'Scurisce i bordi del fondale.',grounding:'Intensità complessiva di ombra e caustica sul fondale.',groundShadow:'Intensità dell’ombra proiettata sul fondale.',groundCaustic:'Intensità della luce concentrata sul fondale.',
 pCount:'Numero dei granelli. Le fibre hanno un conteggio indipendente.',pSize:'Diametro a 1080p. Valori sotto 1 producono polvere fine; il cursore dà più precisione alle misure piccole.',pSizeVar:'Differenza di diametro tra granelli piccoli e grandi.',pSprite:'Sagoma di ogni granello, distinta dalla forma dell’intera struttura.',pOpacity:'Visibilità dei granelli. A 0 restano solo le fibre, se attive.',pSoftness:'Sfuma il bordo dei singoli granelli.',
 pOpening:'A 0 il nucleo è sferico e senza foro. Aumentando apre gradualmente un anello. Le deformazioni restano indipendenti.',pThickness:'Raggio del corpo sferico o spessore del tubo dell’anello.',pFill:'A 0 distribuisce le particelle sulla superficie; a 1 le distribuisce anche dentro il volume.',pClumps:'Concentra la materia in addensamenti lungo la forma.',pLobes:'Numero dei lobi; agisce quando Profondità lobi è sopra 0.',pLobeDepth:'Fa crescere lobi sulla forma. A 0 elimina le sporgenze regolari.',
 pOrganic:'Intensità delle pieghe organiche del campo. A 0 conserva la base geometrica.',pFrequency:'Aumentando, le pieghe organiche diventano più fitte.',pDetail:'Numero di scale di dettaglio sovrapposte al campo organico.',pRough:'Quanto contano le scale più piccole del dettaglio.',pWarp:'Deforma il campo che genera le pieghe organiche.',pNeural:'Raggruppa i percorsi in fasci simili a connessioni neuronali.',pNodes:'Numero dei gruppi della rete; richiede Struttura neuronale sopra 0.',pConnect:'Avvolge e collega i fasci neuronali.',pSymmetry:'Ripete il campo in settori radiali. A 1 non impone simmetria.',
 pLife:'Intensità delle pulsazioni coordinate della materia.',pPulse:'Quante pulsazioni si completano nel loop.',pSignal:'Enfatizza segnali luminosi che attraversano i filamenti.',pPropagation:'Sfalsa l’arrivo delle pulsazioni tra le zone.',pCohesion:'Rende il campo organico più coordinato tra le particelle.',pRandom:'Irregolarità e sfasamento dei percorsi individuali.',pJitter:'Piccoli tremolii della materia.',pVortex:'Avvolge il nucleo in un vortice; il segno cambia il verso.',pReentry:'Richiama periodicamente la materia verso il centro.',pBreath:'Espande e contrae il nucleo insieme.',pTravel:'Ampiezza del percorso orbitale della materia. A 0 mantiene le posizioni di base prima delle altre deformazioni.',pMotionSoftness:'Riduce accelerazioni brusche, dettagli rapidi e microfluttuazioni.',pFollow:'Sfalsa la risposta delle fibre, come un ritardo elastico.',
 pOrbitOval:'Da orbite circolari a ellittiche.',pOrbitTilt:'Inclina i piani delle orbite.',pOrbitPrecession:'Fa oscillare i piani orbitali nel tempo.',pOrbitSpread:'Sfalsa le partenze delle orbite tra le particelle.',pOrbitDrift:'Sposta lentamente i centri delle orbite.',pWander:'Intensità delle correnti casuali periodiche.',pWanderScale:'Scala spaziale delle correnti casuali.',pWanderCycles:'Evoluzioni delle correnti in un loop.',pFlowBalance:'A 0 le zone si muovono insieme, a 1 prevalgono percorsi individuali.',pMotionSeed:'Sceglie una nuova coreografia deterministica, conservando la materia e i colori.',
 pTentacle:'Allunga la stessa materia in bracci; a 0 li disattiva.',pTentacleCount:'Numero dei bracci quando Tentacolarità è attiva.',pTentacleLength:'Quanto lontano si estendono i bracci.',pTentacleTaper:'Concentra la materia in bracci più stretti.',pTentacleCurl:'Avvolge i bracci; il segno inverte il verso.',pTentacleWave:'Ampiezza delle onde che scorrono lungo i bracci.',pTentacleCycles:'Numero delle onde dei tentacoli in un loop.',pSpaceWarp:'Piega l’intero spazio della materia.',pWarpScale:'Scala delle pieghe nello spazio.',pWarpCycles:'Ripetizioni del warp nel loop.',pWarpTwist:'Avvolge le pieghe dello spazio in una torsione.',
 pAttract:'Forza con cui i poli richiamano la materia.',pRepel:'Forza con cui i poli allontanano la materia.',pMagnet:'Avvolge la materia attorno ai poli; il segno cambia verso.',pPoles:'Numero dei poli mobili del campo.',pRadius:'Distanza dei poli dal centro.',pField:'Ampiezza dell’area influenzata da ciascun polo.',pOuter:'Quantità di materia proiettata nei fasci esterni. A 0 li elimina.',pReach:'Estensione dei fasci esterni, quando attivi.',pBranches:'Numero dei fasci esterni, quando attivi.',
 pCycles:'Ripetizioni del moto del campo nel loop.',pDirection:'Inverte il verso del movimento del campo e delle scie.',pRhythm:'Alterna accelerazioni e rallentamenti. A 0 il ritmo è uniforme.',pPause:'Frazione del ciclo trascorsa in pausa.',pSpeedSpread:'Fa compiere a gruppi diversi un numero diverso di giri.',
 pTrailCount:'Numero delle fibre. L’anteprima ne mostra fino a 8.000; l’export usa il numero scelto.',pTrailLength:'Durata della coda come frazione del loop: 1 conserva un giro intero.',pTrailWidth:'Spessore a 1080p. Il cursore offre maggiore precisione sulle fibre più sottili.',pTrailOpacity:'Visibilità delle fibre, indipendente dai granelli.',pTrailFade:'Quanto rapidamente la coda si spegne verso la fine.',pTrailTaper:'Quanto la fibra si assottiglia verso la coda.',pTrailScatter:'Sfalsa il campionamento delle fibre rispetto ai granelli.',pTrailPersistence:'Mantiene luminosa anche la parte più vecchia della coda.',pTrailSoftness:'Sfuma i bordi delle fibre.',pTrailCoherence:'Avvicina i percorsi delle fibre per creare una trama coesa.',pTrailDensity:'Compensa l’accumulo di luce di molte fibre, evitando che il tessuto diventi bianco.',pTrailQuality:'Segmenti usati per ogni curva. Più segmenti rendono lisce le code lunghe; aumentano il costo del rendering.',
 pFiberSheen:'Orienta i riflessi secondo la direzione 3D dei fili. A 0 conserva la resa precedente. Richiede fibre visibili, Lucentezza e Risposta alle luci sopra 0.',pFiberSpread:'Da un riflesso stretto e lucido a una fascia luminosa diffusa. Agisce con Riflesso setoso sopra 0; anche rugosità e dimensione delle luci lo ammorbidiscono.',
 pColorMode:'Sceglie se il colore segue ogni particella, la forma, i fasci oppure una posizione nello spazio.',pColorScatter:'Mescola la palette assegnando colori individuali alle particelle.',pLumaVar:'Varia la luminosità dei singoli granelli senza cambiare la palette.',pDepthFade:'Attenua la materia più lontana dalla vista.',pLighting:'A 0 mostra il colore della palette senza illuminazione. A 1 applica pienamente luci, metallo e iridescenza.',
 environment:'Sceglie la luce ambientale riflessa. Studio è neutro; gli altri ambienti possono aggiungere dominanti.',
 'bg-mode':'Sceglie fondo uniforme, gradiente, fondale o trasparenza per PNG.',
 'material-picker':'Applica una combinazione di parametri della materia.', 'light-rig':'Sostituisce le luci con uno schema pronto.', 'guide-kind':'Sceglie come disegnare il percorso: mano libera, orbita o linea.',
};
const FORCE={strength:'Valori positivi attirano, negativi respingono. A 0 il punto non sposta la materia.',radius:'Distanza di influenza del punto.',swirl:'Fa orbitare la materia attorno al punto; il segno cambia verso.',x:'Posizione orizzontale del punto nella scena.',y:'Posizione verticale del punto nella scena.',z:'Profondità del punto nella scena.',enabled:'Attiva o disattiva questo punto senza eliminarlo.'};
const GUIDE={coverage:'Percentuale stabile di particelle influenzate dal percorso.',strength:'Intensità dell’attrazione o repulsione del percorso.',radius:'Distanza entro cui il percorso influenza la materia.',adherence:'Quanto le particelle seguono l’avanzamento lungo il percorso.',orbitRadius:'Distanza della materia dal centro della curva: a 0 la segue direttamente.',orbitTurns:'Giri della materia attorno alla curva.',cycles:'Ripetizioni del moto lungo il percorso in un loop.',phase:'Sposta il punto di partenza del movimento.',release:'Percentuale del ciclo in cui le particelle restano libere dal percorso.',softness:'Rende più graduali entrata e uscita dall’influenza.',z:'Sposta il percorso in profondità.',closed:'Unisce la fine all’inizio del percorso.',enabled:'Attiva o disattiva il percorso senza cancellarlo.',direction:'Inverte il verso lungo il percorso.',mode:'Segui attira e accompagna; Evita respinge dalla linea.'};
const LIGHT={enabled:'Accende o spegne questa sorgente.',power:'Intensità di questa luce. A 0 la sorgente non illumina.',color:'Colore della sorgente: influenza sia la materia sia i suoi riflessi.',x:'Posizione orizzontale della luce.',y:'Altezza della luce.',z:'Profondità della luce: positiva davanti, negativa dietro.',size:'Dimensione della sorgente e ampiezza del riflesso.',length:'Lunghezza della sorgente.',roll:'Rotazione della sorgente sul suo piano.',softness:'Diffusione dei bordi della sorgente.',cone:'Ampiezza del cono del faretto.',grid:'Numero di elementi della sorgente a griglia.',type:'Forma della sorgente luminosa.',visible:'Mostra direttamente la sorgente anche nel render.'};
const TRACK={enabled:'Attiva questa animazione senza modificare il valore di base.',amplitude:'Quanto si allontana dal valore di base durante l’oscillazione.',cycles:'Ripetizioni di questa animazione nel loop.',phase:'Sposta la partenza dell’animazione rispetto alle altre.',direction:'Inverte il verso di questa animazione.',curve:'Sceglie come accelera e rallenta l’oscillazione.',axis:'Asse attorno al quale orbita la luce.',mode:'Oscillazione va e torna; Giro completo o Scorrimento continuo procede sempre nello stesso verso.'};
export function controlHelp(key){
 if(key.startsWith('body.'))return ({gainX:'Amplifica gli spostamenti orizzontali della camera nel campo creativo.',gainY:'Amplifica gli spostamenti verticali.',offsetX:'Sposta il campo rispetto al centro della scena.',offsetY:'Alza o abbassa il campo rispetto al centro.',rotation:'Ruota gli assi del controllo per compensare la camera obliqua. La calibrazione metrica 4D resta separata.',smoothing:'Tempo di risposta del campo: valori alti rendono i movimenti più morbidi e ritardati.',deadzone:'Ignora oscillazioni molto piccole del punto misurato.',hold:'Dopo la perdita mantiene brevemente la forza prima di attenuarla.',fade:'Tempo impiegato per spegnere il campo dopo l’attesa.',mirrorX:'Inverte la direzione orizzontale.',mirrorY:'Inverte la direzione verticale.',show:'Mostra sulla scena i punti della testa e delle mani, esclusi dagli export.',loss:'Mantieni conserva il campo fermo fino al rientro. Attenua riduce progressivamente la forza.',target:'Campi piega particelle e fibre localmente. Sposta trascina tutta la creazione.',enabled:'Abilita l’influenza di questa parte del corpo.',mode:'Attira avvicina la materia al punto; respingi la allontana. Nello spostamento globale inverte il verso.',strength:'Intensità della risposta a questo punto del corpo.',radius:'Quanto lontano il punto del corpo influenza le particelle.',swirl:'Avvolge le particelle attorno al punto mobile.',z:'Profondità artistica del campo, impostata manualmente.'})[key.split('.').at(-1)];
 if(/^light2?Angle$/.test(key))return 'Sposta la sorgente attorno alla figura in orizzontale.';
 if(/^light2?Height$/.test(key))return 'Regola l’altezza della sorgente luminosa.';
 if(/^light2?Power$/.test(key))return LIGHT.power;
 if(/^light2?Size$/.test(key))return LIGHT.size;
 if(key.startsWith('force.'))return FORCE[key.slice(6)];
 if(key.startsWith('guide.'))return GUIDE[key.slice(6)];
 if(key.startsWith('motions.')||/^lights\.\d+\.(orbit|pulse)\./.test(key))return TRACK[key.split('.').at(-1)];
 if(key.startsWith('lights.'))return LIGHT[key.split('.').at(-1)];
 if(key.startsWith('palette.'))return 'Colore di base della materia. Modifica la casella o inserisci un codice esadecimale; luci e riflessi si aggiungono a questa palette.';
 return HELP[key];
}
