import {LIVING_STYLES,PARTICLE_STUDIES,SPHERE_FORM} from './particle-model.js?v=87dc341942b4';
export function applyLivingStyle(s,style){
 const values=LIVING_STYLES[style];if(!values)return;
 if(s.engine==='solid'&&!s.pLiving&&style!=='off'){
  const example=PARTICLE_STUDIES.find(q=>q.values.pLiving===values.pLiving);
  Object.assign(s,SPHERE_FORM,Object.fromEntries(Object.entries(example.values).filter(([k])=>k.startsWith('p'))));
 }
 Object.assign(s,values);
}
export function livingChooser(s,h){return h.section('Tipo di forma',`<div class="fiber-styles"><button class="outline" data-living-style="off" aria-pressed="${!s.pLiving}">Volume scolpito</button><button class="outline" data-living-style="fibres" aria-pressed="${s.pLiving===1}">Fibre che respirano</button><button class="outline" data-living-style="tissue" aria-pressed="${s.pLiving===2}">Tessuto connesso</button><button class="outline" data-living-style="membrane" aria-pressed="${s.pLiving===3}">Membrana viva</button></div><p class="help">Le strutture vive condividono geometria, palette e movimento con Particelle. Puoi aprire la stessa creazione in entrambi gli spazi.</p>`);}
function composition(s,{slider,details}){return details('Integrazione con le particelle',slider('pLivingBlend',['Solo particelle','Solo struttura'])+`<p class="help">Al centro convivono entrambe; verso gli estremi una componente sfuma. Numero e opacità dei granelli, scie e connessioni restano indipendenti.</p>`+slider('pSurfaceBind',['Nel volume','Sulla struttura'])+slider('pLivingOcclusion',['Nucleo visibile','Pelle schermante'])+`<p class="help">Adesione lega granelli e nodi alla superficie che respira. Le scie conservano i propri percorsi. Schermatura rispetta pori e trasparenza.</p><button class="outline full" data-living-core="true">Aggiungi granelli alla struttura</button><button class="quiet full" data-living-workspace="${s.engine==='solid'?'particles':'solid'}">Apri questa creazione in ${s.engine==='solid'?'Particelle':'Forme'}</button>`);}
export function livingPanel(s,h){
 const {slider,section,details}=h,sliders=keys=>keys.map(k=>slider(k)).join('');
 const select=(key,label,items)=>`<label class="field">${label}<select data-particle-select="${key}">${items.map((n,i)=>`<option value="${i}" ${s[key]===i?'selected':''}>${n}</option>`).join('')}</select></label>`;
 return section('Fibre, tessuto e membrane',(s.engine==='solid'?'':select('pLiving','Struttura connessa',['Spenta','Fasci di fibre','Tessuto','Membrana']))+composition(s,h)+sliders(['pThreadWidth','pStrands','pThreadOpacity','pSkin'])+details('Fasci e intreccio',sliders(['pBundles','pBundleSpread','pWeft','pBundleDelay','pFray'])+'<p class="help">Numero e apertura dei fasci agiscono in modalità Fasci di fibre. Intreccio aggiunge fili trasversali sulla stessa struttura.</p>')+details('Elasticità e pieghe',sliders(['pElastic','pBend','pVolumeHold','pFoldCount','pFoldDepth'])+'<p class="help">I punti collegati resistono allo stiramento; in compressione lasciano richiudere le pieghe senza respingersi. La deformazione è guidata dal moto di Prisma e ripetibile nel loop; non include collisioni.</p>')+details('Pelle, pori e nucleo',sliders(['pSkinOpening','pSkinOffset','pPores','pPoreCount'])+'<p class="help">La pelle è una superficie continua. Apertura la trasforma in una coppa; i pori la forano. I granelli possono aderire alla stessa superficie. Schermatura attenua quelli dietro la pelle in proporzione alla sua opacità. La pelle mostra lo strato più vicino; non simula rifrazione interna.</p>')+details('Respiro e involuzione',sliders(['pInflate','pContract'])+'<p class="help">Apertura e chiusura lente nello stesso loop. Durata e verso sono in Movimento; palette, luci e riflessi restano nelle sezioni Aspetto.</p>')+'<p class="help">Per partire da una forma già bilanciata scegli Fibre che respirano, Tessuto connesso o Membrana viva nei Punti di partenza. Il cambio di struttura conserva palette, luci, durata e campi.</p>');
}
