import {MAX_COLORS,MAX_LIGHTS,LIGHT_META,LIGHT_TYPES,TRACK_META,MATERIAL_STYLES,LEGACY_MATERIAL_STYLES,ENVIRONMENTS,BACKDROPS,LIGHT_SOURCES,LIGHT_RIGS,TEXTURE_STYLES} from './studio-model.js?v=16c153490221';
import {MOODS} from './model.js?v=16c153490221';
import {MOTION_PRESETS,SCULPT_EXAMPLES} from './creative-model.js?v=16c153490221';
export function pathValue(s,path){const parts=path.split('.');let value=s;for(let i=0;i<parts.length;i++){if(i===1&&parts[0]==='lights')value=value.find(l=>l.id===Number(parts[i]));else value=value?.[parts[i]];}return value}
export function pathMeta(path,state){const parts=path.split('.'),last=parts.at(-1);if(last==='cycles')return state?.perfectLoop===false?['Ripetizioni nel ciclo',.1,8,.1]:['Ripetizioni nel loop',1,8,1];if(last==='phase')return['Fase di partenza',0,360,1];if(last==='amplitude'){if(parts[0]==='motions'){const m=TRACK_META[parts[1]];return ['Ampiezza',m[1],m[2],m[3]]}return parts[2]==='orbit'?['Ampiezza orbita',0,180,1]:['Ampiezza pulsazione',0,1,.01]}return LIGHT_META[last]}
export function writePath(s,path,value){const parts=path.split('.');let object=s;for(let i=0;i<parts.length-1;i++){if(i===1&&parts[0]==='lights')object=object.find(l=>l.id===Number(parts[i]));else object=object[parts[i]];}if(object)object[parts.at(-1)]=value}
import {particlePanel} from './particle-panel.js?v=16c153490221';
export function buildPanel(tab,s,h,selectedLight){return s.engine==='particles'?particlePanel(tab,s,h,sharedPanel,selectedLight):sharedPanel(tab,s,h,selectedLight);}
function sharedPanel(tab,s,h,selectedLight){
 const {slider,section,details,colorField,check,icon}=h;
 const regularMoods=MOODS.map((m,i)=>({m,i})).filter(({m})=>!m.referenceFamily);
 const referenceMoods=MOODS.map((m,i)=>({m,i})).filter(({m})=>m.referenceFamily);
 const referenceFamilies=[...new Set(referenceMoods.map(({m})=>m.referenceFamily))];
 const paletteLibrary=()=>details('Palette e mood pronti',`<div class="mood-grid">${regularMoods.slice(0,8).map(({m,i})=>moodButton(m,i)).join('')}</div>`+details(`Altre ${regularMoods.length-8} palette`,`<div class="mood-grid">${regularMoods.slice(8).map(({m,i})=>moodButton(m,i)).join('')}</div>`)+`<button class="quiet full" id="random-palette">${icon('shuffle')}Palette casuale</button>`)
  +details(`Palette dai tuoi riferimenti · ${referenceMoods.length}`,`<p class="help">Palette ispirate ai colori dei tuoi video e delle tue immagini.</p>`+referenceFamilies.map(family=>details(family,`<div class="mood-grid">${referenceMoods.filter(({m})=>m.referenceFamily===family).map(({m,i})=>moodButton(m,i)).join('')}</div>`)).join(''));

 const ps=path=>{const [label,min,max,step]=pathMeta(path,s),v=pathValue(s,path),id='nested-'+path.replaceAll('.','-');return `<div class="param"><div class="param-line"><label for="${id}">${label}</label><input class="number" data-number-path="${path}" type="number" aria-label="${label}: valore" min="${min}" max="${max}" step="${step}" value="${Number(v.toFixed(3))}"></div><input id="${id}" type="range" data-path="${path}" min="${min}" max="${max}" step="${step}" value="${v}" style="--fill:${(v-min)/(max-min)*100}%"></div>`};
 const pc=(path,label)=>`<label class="check"><input type="checkbox" data-path-check="${path}" ${pathValue(s,path)?'checked':''}>${label}</label>`;
 const select=(path,label,items)=>`<label class="field">${label}<select data-path-select="${path}">${items.map(([v,n])=>`<option value="${v}" ${String(pathValue(s,path))===String(v)?'selected':''}>${n}</option>`).join('')}</select></label>`;
 const trackPanel=(path,label,rotation=false,color=false)=>{const cycle=(rotation||color)&&pathValue(s,path+'.mode')==='cycle';return details(label,pc(path+'.enabled','Attiva questo movimento')+(rotation||color?select(path+'.mode','Tipo di movimento',[['wave','Oscillazione'],['cycle',rotation?'Giro completo':'Scorrimento continuo']]):'')+(cycle?'':ps(path+'.amplitude'))+ps(path+'.cycles')+ps(path+'.phase')+select(path+'.direction','Verso',[[1,'Normale'],[-1,'Inverso']])+(cycle?'<p class="help">Movimento continuo a velocità uniforme. Le ripetizioni regolano quanti giri compie nel loop.</p>':select(path+'.curve','Curva di movimento',[['sine','Fluida · sinusoidale'],['soft','Morbida · rallenta al centro'],['triangle','Regolare · triangolare']])))};
 if(tab==='particle-motion')return details('Rotazioni, colori e luci',['rotateX','rotateY','rotateZ'].map(k=>trackPanel('motions.'+k,TRACK_META[k][0],true)).join('')+['gradientOffset','colorWavePhase','iridescence','roughness','transparency','scale','volume','deform','twist','waves'].map(k=>trackPanel('motions.'+k,TRACK_META[k][0],false,k==='gradientOffset'||k==='colorWavePhase')).join('')+slider('motion')+check('environmentRotate','Ruota ambiente')+slider('environmentCycles'));
 if(tab==='particle-light'){const light=s.lights.find(l=>l.id===selectedLight)||s.lights[0],path=light?'lights.'+light.id:'';return section('ILLUMINAZIONE',`<label class="field">Ambiente<select id="environment">${ENVIRONMENTS.map(([v,n])=>`<option value="${v}" ${s.environment===v?'selected':''}>${n}</option>`).join('')}</select></label>`+slider('environmentPower')+slider('environmentAngle'))+section('LUCI',`<button id="add-light" class="outline" ${s.lights.length>=MAX_LIGHTS?'disabled':''}>+ Aggiungi luce</button><div class="light-list">${s.lights.map((l,i)=>`<button data-light-select="${l.id}" class="light-chip ${l===light?'selected':''}">${i+1}</button>`).join('')}</div><button id="show-lights" class="quiet full">Sposta le luci sulla tavola</button>`)+(light?section('LUCE SELEZIONATA',pc(path+'.enabled','Attiva')+ps(path+'.power')+`<label class="color-field">Colore<input type="color" data-path-color="${path}.color" value="${light.color}"></label>`+['x','y','z','size'].map(k=>ps(path+'.'+k)).join('')+`<button data-remove-light="${light.id}" class="quiet danger">Rimuovi luce</button>`)+details('Animazione luce',trackPanel(path+'.orbit','Orbita',true)+select(path+'.orbit.axis','Asse',[['x','X'],['y','Y'],['z','Z']])+trackPanel(path+'.pulse','Pulsazione')):'');}
 if(tab==='shape')return section('FORMA GENERALE',`<button class="quiet full" id="perfect-sphere">${icon('shape')}Sfera perfetta</button>`+slider('volume',['Piatta','Volumetrica'])+slider('deform',['Regolare','Organica'])+slider('scale')+slider('edge',['Netto','Sfumato']))
  +details('Dimensioni e inquadratura',['stretchX','stretchY','stretchZ','positionX','positionY','rotateX','rotateY','rotateZ'].map(k=>slider(k)).join(''))
  +details('Profilo, torsione e curvature',['asymmetry','twist','roundness','taper','bendX','bendY','pinch'].map(k=>slider(k)).join(''))
  +details('Vuoto interno · anelli',['hole','holeX','holeY','holeShape','holeAspect','rimRound'].map(k=>slider(k)).join(''))
  +details('Ritaglio · semilune',['cut','cutX','cutY','cutAspect'].map(k=>slider(k)).join(''))
  +details('Lobi e onde',['lobeAmount','lobes','waves','waveScale'].map(k=>slider(k)).join(''))
  +details('Petali, spine e radici',`<div class="mood-grid">${SCULPT_EXAMPLES.map((q,i)=>`<button class="mood" data-sculpt="${i}">${q.name}</button>`).join('')}</div>`+slider('petalAmount',['Forma di base','Petali / spine'])+slider('petalGrowth',['Sotto la superficie','Emersi'])+slider('petalCount')+slider('petalSharp',['Arrotondati','Aghi'])+slider('petalOpen',['Raccolti','Aperti'])+slider('petalCurl')+slider('petalInflate'))+details('Radici, corde e intrecci',slider('petalWander',['Diritti','Sinuosi'])+slider('petalCoil',['Avvolgi a sinistra','Avvolgi a destra'])+slider('petalReentry',['Verso l’esterno','Entrano ed escono'])+'<p class="help">Emersione fa crescere le appendici dalla superficie. Avvolgimento le curva intorno alla figura; Rientro ne riporta le estremità all’interno.</p>')+details('Superficie e crescita irregolare',slider('petalKnots',['Liscia','Nodosa'])+slider('petalRidges',['Levigata','Nervata'])+slider('petalDisorder',['In ordine','Sfalsate'])+slider('petalRandom',['Uniformi','Lunghezze irregolari']))+details('Innesto nella sfera',`<button id="organic-spines" class="outline full" ${s.petalAmount<=0||s.petalCoverage<=0?'disabled':''}>Rendi organica</button><p class="help">Il raccordo e l’ampiezza della radice sono indipendenti dall’acutezza della punta.</p>`+slider('petalBlend',['Innesto netto','Pelle continua'])+slider('petalRoot',['Radici sottili','Radici ampie']))+details('Proporzioni e distribuzione',slider('petalLength')+slider('petalWidth')+slider('petalCoverage',['Corona','Tutta la sfera'])+slider('petalRows')+slider('petalPhase'))+details('Gambo opzionale',slider('stemAmount')+slider('stemRadius')+slider('stemBend'))
  +details('Esempio completo · Bloom',`<button class="outline full" id="load-bloom-example">Bloom · fiore animato</button><p class="help">Carica insieme forma, colore, materia e movimento.</p>`);
 if(tab==='material')return section('MATERIALI',`<label class="field"><select id="material-picker" aria-label="Materiale iniziale"><option value="">Scegli una materia</option>${MATERIAL_STYLES.map((m,i)=>`<option value="${i}" ${s.renderVersion>=2&&s.materialName===m.name?'selected':''}>${m.name}</option>`).join('')}</select></label><div class="mood-grid materials-grid">${[0,1,5,9].map(i=>`<button class="mood ${s.materialName===MATERIAL_STYLES[i].name?'chosen':''}" data-material="${i}">${MATERIAL_STYLES[i].name}</button>`).join('')}</div>`)+section('LA MATERIA',slider('transparency',['Opaca','Trasparente'])+slider('fullness',['Pellicola','Pieno'])+slider('gloss')+slider('roughness')+slider('metal')+slider('iridescence')+colorField('internalColor','Colore interno'))+details('Trasparenza e diffusione',slider('refraction')+slider('dispersion')+slider('absorption')+slider('tintStrength')+slider('translucency')+slider('scattering')+slider('scatterDirection')+slider('subsurface')+slider('sssRadius')+colorField('sssColor','Colore sottopelle')+`<button id="add-inside-light" class="outline full">${icon('sun')}Una luce dentro la forma</button>`)+details('Guscio, pellicola e vernice',check('thinShellMode','Guscio sottile · sfondo senza distorsione')+slider('hollow')+slider('wallThickness')+slider('thickness')+slider('thinFilm')+slider('filmThickness')+slider('coat')+slider('coatRoughness')+slider('fresnel'))+details('Texture organica',slider('textureDepth',['Liscio','In rilievo'])+slider('textureScale',['Dettagli ampi','Dettagli fini'])+slider('textureOrganic',['Regolare','Irregolare'])+slider('textureAngle')+`<p class="help">Combina grinze, pieghe, abrasioni e increspature sulla stessa materia. Rilievo ne regola l’intensità; Densità e Direzione ne cambiano la distribuzione.</p>`+slider('textureWrinkles')+slider('textureFolds')+slider('textureWear')+slider('textureRipples')+slider('surfaceTexture')+`<div class="mood-grid">${TEXTURE_STYLES.map((t,i)=>`<button class="mood" data-texture-style="${i}">${t.name}</button>`).join('')}</div><button id="reset-texture" class="quiet full">Superficie liscia · azzera texture</button>`)+details('Satinatura e luce propria',['anisotropy','anisotropyAngle','emission'].map(k=>slider(k)).join(''))+details('Materiali precedenti',`<div class="mood-grid">${LEGACY_MATERIAL_STYLES.map((m,i)=>`<button class="mood" data-legacy-material="${i}">${m.name}</button>`).join('')}</div>`);
 if(tab==='color')return section(`LA TUA PALETTE · ${s.palette.length} / ${MAX_COLORS}`,`<div class="editable-palette">${s.palette.map((c,i)=>`<div class="palette-item"><label class="color-swatch"><input type="color" data-palette="${i}" value="${c}" aria-label="Colore ${i+1} della palette"></label><input class="hex-input" data-palette-hex="${i}" value="${c}" aria-label="Codice esadecimale colore ${i+1}" maxlength="7"><div class="color-actions"><button data-color-move="${i}" data-direction="-1" ${i===0?'disabled':''} aria-label="Sposta colore ${i+1} a sinistra">‹</button><button data-color-move="${i}" data-direction="1" ${i===s.palette.length-1?'disabled':''} aria-label="Sposta colore ${i+1} a destra">›</button><button data-color-remove="${i}" ${s.palette.length===1?'disabled':''} aria-label="Rimuovi colore ${i+1}">×</button></div></div>`).join('')}</div><button id="add-color" class="outline full" ${s.palette.length>=MAX_COLORS?'disabled':''}>+ Aggiungi colore</button>`)+section('COME SI INCONTRANO I COLORI',slider('colorSoftness',['Bande nette','Sfumature'])+slider('gradientScale')+slider('gradientAngle')+slider('gradientOffset'))+paletteLibrary()+details('Onde di colore',slider('colorWaveAmount')+slider('colorWaveBands')+slider('colorWavePhase')+details('Direzioni, vortici e sfumature',slider('colorWaveHeight')+slider('colorWaveRadius')+slider('colorWaveSwirl')+slider('colorWaveWarp')))+details('Alone luminoso',slider('glow'));
 if(tab==='light'){
  const light=s.lights.find(l=>l.id===selectedLight)||s.lights[0],index=light?s.lights.indexOf(light):-1,prefix=light?'lights.'+light.id:'';
  const scene=section('ILLUMINAZIONE GENERALE',`<label class="field">Ambiente da riflettere<select id="environment">${ENVIRONMENTS.map(([v,n])=>`<option value="${v}" ${s.environment===v?'selected':''}>${n}</option>`).join('')}</select></label>`+slider('environmentPower'))
   +section('LUCI DELLA SCENA',`<div class="panel-toolbar"><span>${s.lights.length} / ${MAX_LIGHTS} luci</span><button id="add-light" class="outline" ${s.lights.length>=MAX_LIGHTS?'disabled':''}>+ Aggiungi</button></div><div class="light-list">${s.lights.map((l,i)=>`<button data-light-select="${l.id}" class="light-chip ${l===light?'selected':''}" style="--light-color:${l.color}" aria-label="Seleziona luce ${i+1}"><i></i>${i+1}${l.z<0?' · dietro':''}</button>`).join('')}</div><button id="show-lights" class="quiet full">${icon('sun')}Mostra comandi sulla tavola</button><button id="add-inside-light" class="quiet full" ${s.lights.length>=MAX_LIGHTS?'disabled':''}>+ Una luce dentro la forma</button>`);
  const presets=details('Sorgenti e schemi pronti',`<div class="mood-grid">${LIGHT_SOURCES.map((q,i)=>`<button class="mood" data-light-source="${i}" ${s.lights.length>=MAX_LIGHTS?'disabled':''}>+ ${q.name}</button>`).join('')}</div><label class="field">Schema di illuminazione<select id="light-rig"><option value="">Scegli uno schema</option>${LIGHT_RIGS.map((q,i)=>`<option value="${i}">${q.name}</option>`).join('')}</select></label><p class="help">Uno schema sostituisce le sorgenti attuali. Puoi poi modificarle singolarmente.</p>`);
  const environment=details('Direzione e rifrazioni dell’ambiente',slider('environmentAngle')+slider('environmentRefraction'));
  if(!light)return scene+'<p class="help">Aggiungi una luce per illuminare la figura.</p>'+environment+presets;
  return scene+section(`LUCE ${index+1}`,`<div class="panel-toolbar">${pc(prefix+'.enabled','Attiva')}<button data-remove-light="${light.id}" class="quiet danger">Rimuovi</button></div>`+ps(prefix+'.power')+`<label class="color-field">Colore della luce<input type="color" data-path-color="${prefix}.color" value="${light.color}"></label>`)
   +details('Posizione nello spazio',`<div class="mood-grid"><button data-light-depth="front" class="mood">Davanti alla figura</button><button data-light-depth="inside" class="mood">Dentro la figura</button><button data-light-depth="back" class="mood">Dietro la figura</button></div>`+['x','y','z'].map(k=>ps(prefix+'.'+k)).join('')+'<p class="help">Trascina il punto per X e Y. Scorri sul punto, o usa Maiusc mentre trascini, per la profondità Z.</p>')
   +details('Sorgente, forma e diffusione',select(prefix+'.type','Forma della sorgente',LIGHT_TYPES)+pc(prefix+'.visible','Sorgente visibile nella scena')+'<p class="help">La sorgente resta visibile direttamente, attraverso i materiali trasparenti e nei file esportati.</p>'+(light.type==='spot'?['size','softness']:['circle','ring','orb'].includes(light.type)?['size','softness']:['size','length','roll','softness']).map(k=>ps(prefix+'.'+k)).join('')+(light.type==='spot'?ps(prefix+'.cone'):'')+(light.type==='grid'?ps(prefix+'.grid'):''))
   +environment+presets
   +details('Movimento di questa luce',trackPanel(prefix+'.orbit','Orbita',true)+select(prefix+'.orbit.axis','Asse di rotazione',[['x','X · verticale'],['y','Y · orizzontale'],['z','Z · sul piano']])+trackPanel(prefix+'.pulse','Pulsazione di intensità'));
 }
 if(tab==='motion')return section('MOVIMENTO GENERALE',slider('speed')+slider('duration')+slider('motion')+check('perfectLoop','Loop perfetto · stessa forma, colori e luci')+`<p class="help">Durata effettiva: <strong id="effective-duration">${(s.duration/s.speed).toFixed(1)} s</strong> (durata ÷ velocità).</p><p class="help">${s.perfectLoop!==false?'Ogni movimento completa un numero intero di cicli: l’ultimo istante torna al primo, senza salti.':'Le ripetizioni possono essere frazionarie. Alla ripartenza del ciclo forma, colori o luci possono cambiare bruscamente.'}</p>`)
  +details('Movimenti pronti per wallpaper',`<div class="motion-presets">${MOTION_PRESETS.map(([k,n])=>`<button class="mood" data-motion-preset="${k}">${n}</button>`).join('')}</div>`)
  +details('Attiva i movimenti principali',check('animateRotation','Rotazione completa')+check('animateShape','Forma e volume')+check('animateColor','Scorrimento dei colori')+check('animateLight','Orbita di tutte le luci'))
  +`<p class="control-intro">Regola poi ogni elemento nelle sezioni qui sotto. Velocità e durata restano comuni a tutta la scena.</p>`+details('Ambiente e colori della pellicola',check('environmentRotate','Ruota l’ambiente')+slider('environmentCycles')+slider('filmFlow')+slider('filmSwirl')+slider('filmCycles'))+details('Rotazione · 3 assi',['rotateX','rotateY','rotateZ'].map(k=>trackPanel('motions.'+k,TRACK_META[k][0],true)).join(''))+details('Forma · movimenti indipendenti',['volume','deform','twist','waves','hole','cut'].map(k=>trackPanel('motions.'+k,TRACK_META[k][0])).join(''))+details('Radici · crescita e intrecci',['petalGrowth','petalCoil','petalReentry','petalWander'].map(k=>trackPanel('motions.'+k,TRACK_META[k][0])).join('')+'<p class="help">Per un’emersione completa usa «Spuntano e rientrano»: la crescita va da 0 a 1 e torna senza interruzioni.</p>')+details('Radici · superficie e distribuzione',['petalKnots','petalRidges','petalDisorder','petalBlend','petalRoot','petalRandom'].map(k=>trackPanel('motions.'+k,TRACK_META[k][0])).join(''))+details('Petali e gambo · movimenti indipendenti',['petalOpen','petalCurl','petalInflate','petalSharp','petalPhase','stemBend'].map(k=>trackPanel('motions.'+k,TRACK_META[k][0],k==='petalPhase')).join(''))+details('Posizione e dimensione',['positionX','positionY','scale'].map(k=>trackPanel('motions.'+k,TRACK_META[k][0])).join(''))+details('Colori e materia',['colorWavePhase','gradientOffset','iridescence','roughness','transparency'].map(k=>trackPanel('motions.'+k,TRACK_META[k][0],false,k==='gradientOffset'||k==='colorWavePhase')).join(''))+details('Ogni singola luce',s.lights.length?s.lights.map((l,i)=>details(`Luce ${i+1}`,trackPanel(`lights.${l.id}.orbit`,'Orbita',true)+select(`lights.${l.id}.orbit.axis`,'Asse',[['x','X'],['y','Y'],['z','Z']])+trackPanel(`lights.${l.id}.pulse`,'Intensità'))).join(''):'<p class="help">Aggiungi una luce nel pannello Luci.</p>')+`<p class="help">L’esportazione a 60 fps calcola ogni fotogramma del movimento.</p>`;
 if(tab==='photo')return `<p class="control-intro">Regola la resa fotografica. Gli effetti vengono conservati anche nei download.</p>`+section('TONI',slider('exposure')+slider('brightness')+slider('contrast')+slider('saturation'))+check('photoAll','Applica le regolazioni anche allo sfondo')+details('Bilanciamento e gamma',['temperature','photoTint','gamma','blacks','highlights'].map(k=>slider(k)).join(''))+details('Lente e finitura',slider('lensDistortion',['Barilotto','Cuscinetto'])+slider('vignette')+slider('grain')+slider('grainSize'))+`<button id="reset-photo" class="quiet full">${icon('reset')}Azzera le regolazioni fotografiche</button>`;
 if(tab==='background'){
 const backdropGrid=dark=>`<div class="backdrop-grid">${BACKDROPS.map((b,i)=>({b,i})).filter(({b})=>!!b.dark===dark).map(({b,i})=>`<button class="backdrop-card ${s.bgMode===(b.mode||'studio')&&s.background===b.colors[0]&&s.background2===b.colors[1]?'chosen':''}" data-backdrop="${i}" aria-label="Fondale ${b.name}"><i style="background:linear-gradient(180deg,${b.colors[0]} 42%,${b.colors[1]} 100%)"></i><span>${b.name}<small>${b.mode==='solid'?'Tinta piena':'Sfumatura morbida'}</small></span></button>`).join('')}</div>`;
 return section('FONDO',`<label class="field">Tipo di sfondo<select id="bg-mode"><option value="solid" ${s.bgMode==='solid'?'selected':''}>Tinta unita</option><option value="gradient" ${s.bgMode==='gradient'?'selected':''}>Gradiente</option><option value="studio" ${s.bgMode==='studio'?'selected':''}>Fondale morbido</option><option value="transparent" ${s.bgMode==='transparent'?'selected':''}>Trasparente</option></select></label>${colorField('background',s.bgMode==='studio'?'Colore superiore':'Colore di sfondo')}${['gradient','studio'].includes(s.bgMode)?colorField('background2',s.bgMode==='studio'?'Colore della base':'Secondo colore'):''}${s.bgMode==='gradient'?slider('bgAngle'):''}${s.bgMode==='studio'?slider('bgHeight')+slider('bgSoftness')+details('Luce del fondale',slider('bgWash')+slider('bgShade')):''}${s.bgMode==='transparent'?'<p class="help">La scacchiera nell’anteprima viene rifratta dalla forma. PNG e WebP la escludono e conservano l’alpha; JPEG e video usano il colore di sfondo.</p>':''}`)+details('Fondali neri e grigi',backdropGrid(true)+`<p class="help">Neri pieni, grigi profondi e sfumature appena accennate. Ogni colore è modificabile.</p>`)+details('Fondali chiari · 8 varianti',backdropGrid(false))+details('Composizione',slider('scale')+slider('positionX')+slider('positionY'))+details('Ombra e caustica',slider('grounding')+slider('groundShadow')+slider('groundCaustic'));
 }
 return '';
}
function moodButton(m,i){return `<button class="mood" data-mood="${i}"><span class="mood-dots">${m.colors.map(c=>`<i style="background:${c}"></i>`).join('')}</span>${m.name}</button>`}
