import {META,MOODS,GROUPS} from './model.js';
import {newLight,MAX_LIGHTS,MAX_COLORS,LIGHT_META,LIGHT_TYPES,MATERIAL_STYLES,SHAPE_TRACKS} from './studio-model.js';
import {material,sculpt,motionPreset,upgrade,setFullness} from './creative-model.js';

const normalize=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[’']/g,' ').trim();
const isColor=c=>typeof c==='string'&&/^#[0-9a-f]{6}$/i.test(c);
const namedColors={nero:'#000000',nera:'#000000',bianco:'#ffffff',bianca:'#ffffff',rosso:'#ff305e',rossa:'#ff305e',rosa:'#ff69b4',blu:'#365eff',azzurro:'#87cfff',azzurra:'#87cfff',ciano:'#4de5ef',cyan:'#4de5ef',viola:'#ad75ff',verde:'#75d9a5',giallo:'#ffe18b',gialla:'#ffe18b',arancione:'#ff985c',grigio:'#6c7280',grigia:'#6c7280',argento:'#c8d3e0',oro:'#e6bc64',lavanda:'#b7a3ea',salvia:'#a6bbaa',corallo:'#ff736d',turchese:'#49cec3',petrolio:'#145461',crema:'#eee1c9',avorio:'#f5eedc'};
function colorsIn(text){const result=[];const re=/#(?:[0-9a-f]{6}|[0-9a-f]{3})\b|\b(?:nero|nera|bianco|bianca|rosso|rossa|rosa|blu|azzurro|azzurra|ciano|cyan|viola|verde|giallo|gialla|arancione|grigio|grigia|argento|oro|lavanda|salvia|corallo|turchese|petrolio|crema|avorio)\b/gi;for(const m of text.matchAll(re)){let c=m[0][0]==='#'?m[0].toLowerCase():namedColors[m[0].toLowerCase()];if(c.length===4)c='#'+c.slice(1).split('').map(q=>q+q).join('');result.push(c);}return result;}
function scalar(key,value){const m=Object.hasOwn(META,key)?META[key]:null;if(!m||!Number.isFinite(value)||value<m[1]||value>m[2])throw Error('Valore non valido per '+(m?.[0]||key));return m[3]>=1?Math.round(value):value;}
const shapeNames=['sfera','goccia','blob','macchia','disco','anello','semiluna','riccio','borchie','aghi','rosetta'];
function shape(s,name){if(!shapeNames.includes(name))throw Error('Forma non disponibile');for(const k of ['deform','asymmetry','twist','waves','hole','cut','edge','roundness','taper','bendX','bendY','lobeAmount','pinch','rimRound','petalAmount','petalBlend','petalRoot','petalRandom','stemAmount'])s[k]=0;for(const k of ['volume','stretchX','stretchY','stretchZ','holeAspect','cutAspect'])s[k]=1;for(const k of SHAPE_TRACKS)s.motions[k].enabled=false;
 if(name==='goccia')Object.assign(s,{taper:.38,stretchY:1.18,stretchX:.9});if(name==='blob')Object.assign(s,{deform:.3,asymmetry:.13,twist:.3});if(name==='macchia')Object.assign(s,{volume:.08,stretchX:1.2,deform:.34,edge:.22});if(name==='disco')s.volume=.1;if(name==='anello')Object.assign(s,{hole:.55,volume:.45});if(name==='semiluna')Object.assign(s,{cut:.9,cutX:.4,cutY:.1,volume:.5});const i=['rosetta','riccio','borchie','aghi'].indexOf(name);if(i>=0)sculpt(s,i);return s;}

// Atomic, allowlisted operations shared by text commands and browser agents.
// No generated code is evaluated and an invalid plan never changes the editor.
export function applyDescriptionPlan(current,plan){
 if(!plan||!Array.isArray(plan.operations)||plan.operations.length>100)throw Error('La richiesta non contiene modifiche valide.');const s=structuredClone(current);const notes=[];
 for(const o of plan.operations){if(!o||typeof o!=='object')throw Error('Comando non valido');
  if(o.type==='set'){const value=scalar(o.key,o.value);if(GROUPS.material.includes(o.key)||/^(environment|film|petal|stem|colorWave|ground)/.test(o.key))upgrade(s);s[o.key]=value;if(o.key==='fullness')setFullness(s,value);notes.push(META[o.key][0]);}
  else if(o.type==='shape'){upgrade(s);shape(s,o.name);notes.push('Forma: '+o.name);}
  else if(o.type==='material'){if(!Number.isInteger(o.index)||!MATERIAL_STYLES[o.index])throw Error('Materia non disponibile');material(s,o.index);notes.push('Materia: '+MATERIAL_STYLES[o.index].name);}
  else if(o.type==='palette'){if(!Array.isArray(o.colors)||!o.colors.length||o.colors.length>MAX_COLORS||!o.colors.every(isColor))throw Error('Palette non valida');s.palette=o.colors.map(c=>c.toLowerCase());notes.push('Palette');}
  else if(o.type==='addColor'){if(!isColor(o.color)||s.palette.length>=MAX_COLORS)throw Error('Puoi usare fino a 12 colori');s.palette.push(o.color.toLowerCase());notes.push('Colore aggiunto');}
  else if(o.type==='removeColor'){if(s.palette.length<=1)throw Error('Conserva almeno un colore');if(!Number.isInteger(o.index)||o.index<0||o.index>=s.palette.length)throw Error('Colore non trovato');s.palette.splice(o.index,1);notes.push('Colore rimosso');}
  else if(o.type==='color'){if(!['internalColor','sssColor'].includes(o.key)||!isColor(o.value))throw Error('Colore non valido');upgrade(s);s[o.key]=o.value;notes.push(o.key==='internalColor'?'Colore interno':'Colore sottopelle');}
  else if(o.type==='background'){if(!['solid','gradient','transparent','studio'].includes(o.mode))throw Error('Sfondo non valido');if(o.colors&&(!Array.isArray(o.colors)||!o.colors.length||!o.colors.every(isColor)))throw Error('Colori dello sfondo non validi');s.bgMode=o.mode;if(o.colors){s.background=o.colors[0];s.background2=o.colors[1]||o.colors[0];}notes.push('Sfondo');}
  else if(o.type==='environment'){if(!['studio','sky','sunset','neon','aurora','aquarium','city'].includes(o.name))throw Error('Ambiente non valido');upgrade(s);s.environment=o.name;notes.push('Ambiente riflesso');}
  else if(o.type==='light'){upgrade(s);if(o.action==='remove'){const i=s.lights.findIndex(l=>l.id===o.id);if(i<0)throw Error('Luce non trovata');s.lights.splice(i,1);notes.push('Luce rimossa');continue;}let l;if(o.action==='add'){if(s.lights.length>=MAX_LIGHTS)throw Error('Puoi usare fino a 8 luci');l=newLight(Math.max(0,...s.lights.map(q=>q.id))+1);}else if(o.action==='edit'){l=s.lights.find(q=>q.id===o.id);if(!l)throw Error('Luce non trovata');}else throw Error('Azione luce non valida');for(const [k,v] of Object.entries(o.values||{})){if(Object.hasOwn(LIGHT_META,k)){const m=LIGHT_META[k];if(!Number.isFinite(v)||v<m[1]||v>m[2])throw Error('Valore luce non valido');l[k]=m[3]>=1?Math.round(v):v;}else if(k==='color'&&isColor(v))l.color=v;else if(k==='type'&&LIGHT_TYPES.some(q=>q[0]===v))l.type=v;else if(['visible','enabled'].includes(k)&&typeof v==='boolean')l[k]=v;else throw Error('Proprietà luce non valida');}if(o.action==='add')s.lights.push(l);notes.push(o.action==='add'?'Luce aggiunta':'Luce spostata / modificata');}
  else if(o.type==='motionPreset'){if(!['bloom','chromatic','breathe','reflect','film','orbit','wave'].includes(o.name))throw Error('Movimento non disponibile');motionPreset(s,o.name);notes.push('Movimento');}
  else if(o.type==='stopMotion'){for(const t of Object.values(s.motions))t.enabled=false;for(const l of s.lights){l.orbit.enabled=false;l.pulse.enabled=false;}s.environmentRotate=false;s.filmFlow=0;s.filmSwirl=0;notes.push('Animazione ferma');}
  else throw Error('Comando non disponibile');
 }
 return {state:s,notes:[...new Set(notes)],changed:JSON.stringify(s)!==JSON.stringify(current)};
}

const attributes=[
 ['trasparen(?:za|te|ti)','transparency',.2],['metall(?:o|ico|ica|ici|izzata|izzato)','metal',.2],['iridescen(?:za|te|ti)','iridescence',.2],['lucen(?:tezza|te|ti)|lucid(?:o|a|e|i)','gloss',.2],['rugos(?:ita|o|a)|ruvid(?:o|a)','roughness',.2],['spessor(?:e)|pien(?:ezza|o|a)','fullness',.2],['vuot(?:ezza|o|a)','hollow',.2],['scattering|diffusione interna','scattering',.2],['subsurface|sss|sottopelle','subsurface',.2],['organica|organico|organicita','deform',.08],['allungat(?:a|o)|alta|alto','stretchY',.2],['schiacciat(?:a|o)|appiattit(?:a|o)|piatta|piatto','volume',-.2],['grand(?:e|i)','scale',.15],['piccol(?:a|o|e|i)','scale',-.15],['contrasto','contrast',.2],['luminosita|luminos(?:a|o)','brightness',.1],['scur(?:a|o)','brightness',-.1],['esposizione','exposure',.35],['saturazione|saturat(?:a|o)','saturation',.2],['grana','grain',.025],['distorsione','lensDistortion',.1],['alone|bagliore','glow',.1],['caustica','groundCaustic',.2],['ombra(?: sul fondale)?','groundShadow',.2],['sfumat(?:a|o|e|i)|morbidezza del contorno','edge',.08],['acut(?:a|o|e|i)|affilat(?:a|o|e|i)','petalSharp',.2]
];
function aliases(){const extra=[['metallo','metal'],['trasparente','transparency'],['iridescente','iridescence'],['lucentezza','gloss'],['lucido','gloss'],['rugosita','roughness'],['spessore','fullness'],['vuotezza','hollow'],['scattering','scattering'],['sss','subsurface'],['sfumatura','edge'],['alone','glow'],['caustica','groundCaustic'],['ombra','groundShadow'],['dimensione','scale'],['lunghezza spine','petalLength'],['acutezza','petalSharp'],['curvatura spine','petalCurl'],['fusione','petalBlend'],['radici','petalRoot'],['irregolarita','petalRandom'],['durata','duration']];return [...extra,...Object.entries(META).flatMap(([key,m])=>[[normalize(key),key],[normalize(m[0]).replace(/\s*·.*$/,''),key]])].sort((a,b)=>b[0].length-a[0].length);}
function escapeRe(s){return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');}
const keyAliases=aliases();
const setting=(key,value)=>({type:'set',key,value:Math.max(META[key][1],Math.min(META[key][2],value))});

// This is deliberately a local command interpreter, not an AI model.
// Unsupported clauses are reported, never represented as understood.
export function interpretDescription(text,current){
 if(typeof text!=='string'||text.trim().length<2||text.length>1600)throw Error('Scrivi una descrizione tra 2 e 1600 caratteri.');const operations=[],unrecognized=[];
 const clauses=normalize(text).split(/[,;\n](?!\d)|\s+e\s+(?=(?:sfondo|aggiung|tog|rimuov|rend|fai|metti|sposta|trasparen|metallo|luce|luci|palette|senza)\b)/).map(q=>q.trim()).filter(Boolean);
 let working=structuredClone(current);
 for(const clause of clauses){const start=operations.length,colors=colorsIn(clause),negative=/\b(?:senza|togli|togliere|rimuov\w*|elimina\w*|spegni|zero|nessun\w*|no)\b/.test(clause)||/^non\s+(?:trasparen|metall|iridescen|lucid|rugos)/.test(clause),less=/\bmeno\b/.test(clause),strong=/\b(?:molto|tant\w*|massim\w*|completamente)\b/.test(clause),factor=strong?1.7:1;
  if(/\b(?:non cambiare|mantieni|conserva|lascia invariat)/.test(clause))continue;
  let materialWords='',exact=false;for(const [label,key] of keyAliases){const re=new RegExp('(?:^|\\b)'+escapeRe(label)+'\\s*(?:[:=]|(?:a|al|di|del|circa)\\s+)?\\s*(-?\\d+(?:[.,]\\d+)?)\\s*(%|percento|per cento)?(?:\\s|$)','i'),m=clause.match(re);if(m){let v=Number(m[1].replace(',','.'));if(m[2])v=META[key][1]+(META[key][2]-META[key][1])*v/100;operations.push(setting(key,v));exact=true;break;}}
  if(!exact){
   const form=shapeNames.find(q=>new RegExp('\\b'+q+'\\b').test(clause));if(form&& !/\bspine|punte|aghi|borchie|petali\b/.test(clause.replace(form,''))&&!/\bpiu|meno|non\b/.test(clause))operations.push({type:'shape',name:form});
   if(/\bspine|punte|aghi|borchie|petali\b/.test(clause)){
    if(/\borganic\w*|integrat\w*|fuse|fus[ae]|raccordat\w*|naturali\b/.test(clause)){if(working.petalAmount<=0)operations.push({type:'shape',name:'riccio'});operations.push(setting('petalBlend',Math.max(.8,working.petalBlend)),setting('petalRoot',Math.max(.55,working.petalRoot)),setting('petalRandom',Math.max(.24,working.petalRandom)));}
    if(/\bcurv\w*|arricci\w*|piegat\w*\b/.test(clause))operations.push(setting('petalCurl',working.petalCurl+(less?-.22:.22)*factor));
    if(/\bcort\w*|lung\w*\b/.test(clause))operations.push(setting('petalLength',working.petalLength+(/\bcort\w*\b/.test(clause)?-.2:.2)*factor));
    if(/\bappuntit\w*|acut\w*|affilat\w*\b/.test(clause))operations.push(setting('petalSharp',working.petalSharp+(less?-.2:.2)*factor));
    if(/\birregolar\w*|casuali\b/.test(clause))operations.push(setting('petalRandom',working.petalRandom+(less?-.2:.2)*factor));
    if(negative)operations.push(setting('petalAmount',0));
   }
   const materialAliases=[...MATERIAL_STYLES.map((q,i)=>[new RegExp('\\b'+escapeRe(normalize(q.name))+'\\b'),i]).sort((a,b)=>b[0].source.length-a[0].source.length),[/\bbolla\b/,0],[/\bcromo\b/,11],[/\b(?:acqua|vetro|cristallo|gelatina|ghiaccio|perla|ceramica|satinato|opaco|silicone)\b/,null]];if(!negative&&!less&&!/\b(?:piu|meno)\b/.test(clause)){for(const [re,index] of materialAliases){const m=clause.match(re);if(m){const i=index??MATERIAL_STYLES.findIndex(q=>normalize(q.name).includes(m[0]==='acqua'?'goccia':m[0]));if(i>=0){operations.push({type:'material',index:i});materialWords=m[0];}break;}}}
   if(/\bsfondo|fondale|background\b/.test(clause)){const mode=/\btrasparen\w*\b/.test(clause)?'transparent':/gradient|sfumat/.test(clause)?'gradient':'solid';if(colors.length||mode==='transparent')operations.push({type:'background',mode,colors:colors.length?colors:undefined});}
   else if(/\bluce|luci|neon|faro|softbox|alogeno\b/.test(clause)){
    const target=clause.match(/\bluce\s*(\d+)/),id=target?+target[1]:working.lights.find(l=>l.enabled)?.id;
    if(negative){if(id)operations.push({type:'light',action:'remove',id});}
    else{const type=/\bbarra|neon\b/.test(clause)?'bar':/\banello|alogeno\b/.test(clause)?'ring':/\bfaro\b/.test(clause)?'spot':/\bgriglia\b/.test(clause)?'grid':/\bsoftbox|diffusore\b/.test(clause)?'diffuser':'circle';const add=/\baggiung\w*|nuov\w*|metti|inserisci\b/.test(clause)||!id,values={};if(add){Object.assign(values,{type,visible:true,power:1.8});if(type==='bar')Object.assign(values,{size:.06,length:1.2,softness:.06});}else if(/\bbarra|anello|faro|griglia|softbox|diffusore\b/.test(clause))values.type=type;if(colors.length)values.color=colors[0];if(/\bdietro\b/.test(clause))values.z=-2;if(/\bdavanti\b/.test(clause))values.z=2;if(/\bdentro|intern\w*\b/.test(clause))Object.assign(values,{x:0,y:0,z:0,type:'orb',size:.12,length:.12});if(/\bsinistra\b/.test(clause))values.x=-1.7;if(/\bdestra\b/.test(clause))values.x=1.7;if(/\balto|sopra\b/.test(clause))values.y=1.6;if(/\bbasso|sotto\b/.test(clause))values.y=-1.6;if(/\bpiu forte|piu intensa|meno intensa\b/.test(clause))values.power=(working.lights.find(l=>l.id===id)?.power||1.8)+(less?-.5:.5);if(add||Object.keys(values).length)operations.push({type:'light',action:add?'add':'edit',id,values});}
   }
   else if(negative&&/\bcolore\s*(?:\d+|ultimo|finale)|\bultimo colore\b/.test(clause)){const m=clause.match(/colore\s*(\d+)/);operations.push({type:'removeColor',index:m?Number(m[1])-1:working.palette.length-1});}
   else if(colors.length){if(/\bsottopelle|sss\b/.test(clause))operations.push({type:'color',key:'sssColor',value:colors[0]});else if(/\binterno|interna\b/.test(clause))operations.push({type:'color',key:'internalColor',value:colors[0]});else if(/\baggiung\w*\b/.test(clause))for(const c of colors)operations.push({type:'addColor',color:c});else if(negative){const index=working.palette.findIndex(c=>colors.includes(c));if(index>=0)operations.push({type:'removeColor',index});}else operations.push({type:'palette',colors});}
   const mood=MOODS.find(q=>clause.includes(normalize(q.name)));if(mood&&/palette|mood/.test(clause))operations.push({type:'palette',colors:mood.colors});
   if(!/\bsfondo|fondale|luce|luci|neon\b/.test(clause)){const attributeState=applyDescriptionPlan(current,{operations}).state,attributeText=materialWords?clause.replace(materialWords,''):clause;for(const [pattern,key,delta] of attributes){if(new RegExp('\\b(?:'+pattern+')\\b').test(attributeText)&&!(key==='deform'&&/spine|punte|aghi|borchie|petali/.test(clause))){let v=negative?META[key][1]:/\bmassim\w*|completamente\b/.test(clause)?META[key][delta<0?1:2]:attributeState[key]+delta*(less?-1:1)*factor;operations.push(setting(key,v));}}}
   if(/\bferma|stop|senza movimento|senza animazione\b/.test(clause))operations.push({type:'stopMotion'});
   else{const movement=/riflessi.*gir|rotazione.*riflessi/.test(clause)?'reflect':/luce.*orbit/.test(clause)?'orbit':/colori.*(?:col|vortic)/.test(clause)?'film':/respir/.test(clause)?'breathe':/ondegg/.test(clause)?'wave':/petali.*(?:aprono|apertura)/.test(clause)?'bloom':null;if(movement)operations.push({type:'motionPreset',name:movement});if(/\bpiu lent\w*|rallenta|rilassant\w*\b/.test(clause))operations.push(setting('duration',Math.max(16,working.duration+4)));if(/\bpiu veloc\w*|accelera\b/.test(clause))operations.push(setting('duration',working.duration-3));}
  }
  if(operations.length===start)unrecognized.push(clause);else working=applyDescriptionPlan(current,{operations}).state;
 }
 return {operations,unrecognized};
}

export function descriptionCatalog(){return {parameters:Object.fromEntries(Object.entries(META).map(([k,m])=>[k,{label:m[0],min:m[1],max:m[2],step:m[3]}])),materials:MATERIAL_STYLES.map((m,index)=>({index,name:m.name})),shapes:shapeNames,lightTypes:LIGHT_TYPES,lightParameters:LIGHT_META,maxLights:MAX_LIGHTS,maxColors:MAX_COLORS};}
