import assert from 'node:assert/strict';
import {newCreation,sculpt} from '../prisma-studio/dist/creative-model.js';
import {interpretDescription,applyDescriptionPlan,descriptionCatalog} from '../prisma-studio/dist/description.js';
const base=sculpt(newCreation(),3);base.deform=.17;base.hole=.12;base.rotateY=37;
const run=(text,state=base)=>{const plan=interpretDescription(text,state),result=applyDescriptionPlan(state,plan);console.log(JSON.stringify({text,notes:result.notes,unrecognized:plan.unrecognized}));return {...result,plan};};
let r=run('Radici che entrano ed escono dalla sfera');assert(r.state.petalReentry>.5);assert.equal(r.state.hole,.12);assert.equal(r.state.rotateY,37);assert.equal(r.state.deform,.17);assert(r.state.petalAmount>0);assert.deepEqual(r.plan.unrecognized,[]);
r=run('Spine nervose e nodose, meno geometricamente ordinate');assert(r.state.petalKnots>.3);assert(r.state.petalDisorder>0);assert.equal(r.state.roughness,base.roughness);assert.deepEqual(r.plan.unrecognized,[]);
r=run('Piccoli rigonfiamenti di una sfera');assert(r.state.petalLength<base.petalLength);assert(r.state.petalGrowth<1);assert(r.state.petalAmount>0);assert.equal(r.state.hole,.12);assert.deepEqual(r.plan.unrecognized,[]);
r=run('Corde che si attorcigliano attorno alla sfera');assert(r.state.petalCoil>.3);assert(r.state.petalAmount>0);assert.equal(r.state.hole,.12);assert.deepEqual(r.plan.unrecognized,[]);
r=run('Falle comparire gradualemnte e poi sparire');assert(r.state.motions.petalGrowth.enabled);assert.equal(r.state.motions.petalGrowth.phase,270);assert.deepEqual(r.plan.unrecognized,[]);
r=run('Spie nerborute, raidi che entrano ed escono dallas sfera, falle attorcigliarsdi nel movimento');assert(r.state.petalKnots>0);assert(r.state.motions.petalCoil.enabled);assert.deepEqual(r.plan.unrecognized,[]);
r=run('Palette blu e viola e sfondo nero e aggiungi una luce rosa dietro');assert.deepEqual(r.state.palette,['#365eff','#ad75ff']);assert.equal(r.state.background,'#000000');assert.equal(r.state.lights.at(-1).color,'#ff69b4');assert(r.state.lights.at(-1).z<0);assert.deepEqual(r.plan.unrecognized,[]);
r=run('Più curve e meno appuntite',base);assert(r.state.petalCurl>base.petalCurl);assert(r.state.petalSharp<base.petalSharp);assert.deepEqual(r.plan.unrecognized,[]);
r=run('Spine più curve e senza grana');assert(r.state.petalCurl>base.petalCurl);assert.equal(r.state.grain,0);assert.equal(r.state.petalAmount,base.petalAmount);assert.deepEqual(r.plan.unrecognized,[]);
r=run('Spine più curve e con occhi di drago');assert(r.state.petalCurl>base.petalCurl);assert(r.plan.unrecognized.some(s=>s.includes('occhi')&&s.includes('drago')));
r=run('Trasparenza 80% metallo 25% nodosità 60%');assert.equal(r.state.transparency,.8);assert.equal(r.state.metal,.25);assert.equal(r.state.petalKnots,.6);assert.deepEqual(r.plan.unrecognized,[]);
r=run('Spine meno curve e più nodose');assert(r.state.petalCurl<base.petalCurl);assert(r.state.petalKnots>0);assert.deepEqual(r.plan.unrecognized,[]);
r=run('Non cambiare materiale, spine più curve');assert.equal(r.state.materialName,base.materialName);assert(r.state.petalCurl>base.petalCurl);assert.deepEqual(r.plan.unrecognized,[]);
r=run('Radici in movimento che entrano ed escono');assert(r.state.motions.petalGrowth.enabled);assert(r.state.motions.petalCoil.enabled);assert.deepEqual(r.plan.unrecognized,[]);
r=run('Anima i nodi delle radici');assert(r.state.motions.petalKnots.enabled);assert.deepEqual(r.plan.unrecognized,[]);
r=run('Sfera perfetta');assert.equal(r.state.petalAmount,0);assert.equal(r.state.petalGrowth,1);assert.equal(r.state.petalWander,0);assert.equal(r.state.hole,0);
assert(descriptionCatalog().shapes.includes('radici intrecciate'));assert(descriptionCatalog().motionTracks.petalGrowth);
const original=structuredClone(base);assert.throws(()=>applyDescriptionPlan(base,{operations:[{type:'set',key:'petalKnots',value:.5},{type:'motionTrack',key:'petalGrowth',values:{evil:true}}]}));assert.deepEqual(base,original);
assert.throws(()=>applyDescriptionPlan(base,{operations:[{type:'motionTrack',key:'petalGrowth',values:{mode:'cycle'}}]}));
console.log('User examples, typos, target scopes, unknown fragments, multiple numeric commands and atomic validation: PASS');
r=run('Disattiva il loop perfetto, durata del loop 20 secondi, velocità del movimento 0,5x');assert.equal(r.state.perfectLoop,false);assert.equal(r.state.duration,20);assert.equal(r.state.speed,.5);assert.deepEqual(r.plan.unrecognized,[]);
let free=applyDescriptionPlan(r.state,{operations:[{type:'motionTrack',key:'petalGrowth',values:{enabled:true,cycles:1.3}}]}).state;assert.equal(free.motions.petalGrowth.cycles,1.3);
r=run('Attiva il loop perfetto',free);assert.equal(r.state.perfectLoop,true);assert.equal(r.state.motions.petalGrowth.cycles,1);assert.deepEqual(r.plan.unrecognized,[]);
r=run('Non farle comparire',free);assert.equal(r.state.motions.petalGrowth.enabled,false);assert.deepEqual(r.plan.unrecognized,[]);
r=run('Radici nere su sfondo bianco con luce blu dietro');assert.deepEqual(r.state.palette,['#000000']);assert.equal(r.state.background,'#ffffff');assert.equal(r.state.lights[0].color,'#365eff');assert(r.state.lights[0].z<0);assert.deepEqual(r.plan.unrecognized,[]);
r=run('Spine senza nodi e meno ordinate');assert.equal(r.state.petalKnots,0);assert(r.state.petalDisorder>0);assert(r.state.petalAmount>0);assert.deepEqual(r.plan.unrecognized,[]);
r=run('Crea una sfera opaca');assert.equal(r.state.transparency,0);assert.equal(r.state.petalAmount,0);assert.deepEqual(r.plan.unrecognized,[]);
console.log('Loop modes, precise duration/speed, motion negation, adjective colors and scoped negatives: PASS');
r=run('Luce 1 intensità 3 x 1 z -2');assert.equal(r.state.lights[0].power,3);assert.equal(r.state.lights[0].x,1);assert.equal(r.state.lights[0].z,-2);assert.deepEqual(r.plan.unrecognized,[]);
r=run('Rotazione verticale 45');assert.equal(r.state.rotateX,45);assert.equal(r.state.motions.rotateX.enabled,false);assert.deepEqual(r.plan.unrecognized,[]);
console.log('Numeric light editing and static rotation: PASS');
r=run('metallo');assert.equal(r.state.materialName,'Metallo liquido');assert.equal(r.state.metal,1);assert.deepEqual(r.plan.unrecognized,[]);
r=run('più metallo');assert(r.state.metal>base.metal);assert.equal(r.state.materialName,base.materialName);
console.log('Material names and relative metallicity: PASS');
