from pathlib import Path
from playwright.sync_api import sync_playwright
import json,subprocess
out=Path('/workspace/prisma-performance-audit');state=json.loads(subprocess.check_output(['node','--input-type=module','-e',"import{newCreation,material}from'./dist/creative-model.js';let s=newCreation();material(s,14);console.log(JSON.stringify(s));"],cwd='/workspace/prisma-studio'))
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox','--use-angle=gl-egl','--ignore-gpu-blocklist','--disable-gpu-sandbox']);page=b.new_page(viewport={'width':1280,'height':920});page.set_default_timeout(30000);errors=[];page.on('pageerror',lambda e:errors.append(str(e)));page.add_init_script('window.testTools={};Object.defineProperty(document,"modelContext",{value:{registerTool(t){testTools[t.name]=t}}});');page.add_init_script("if(!localStorage.getItem('perf-test')){localStorage.setItem('prisma-current-v2',"+json.dumps(json.dumps({'state':state,'ratio':1,'phase':0}))+ ");localStorage.setItem('perf-test','1');}")
 # Isolate UI/state tests; actual renderer/pixel comparisons run independently.
 page.route('**/renderer-real.js',lambda r:r.fulfill(path='/workspace/prisma-studio/dist/renderer.js',content_type='text/javascript'));page.route('**/renderer.js',lambda r:r.fulfill(body='import{Renderer as Base,fieldAt,sampleFrame}from"./renderer-real.js";export{fieldAt,sampleFrame};export class Renderer extends Base{draw(s,p,w,h){this.canvas.width=w;this.canvas.height=h;}}',content_type='text/javascript'))
 page.goto('http://127.0.0.1:4173/',wait_until='networkidle');read=lambda:page.evaluate('testTools.read_creation.execute()');before=read();page.locator('#performance-open').click();assert page.locator('#gpu-name').inner_text();page.locator('#preview-quality').select_option('fluid');page.locator('[aria-label="Chiudi prestazioni"]').click();page.wait_for_timeout(700);fluid=page.locator('#art').evaluate('(c)=>Math.max(c.width,c.height)');assert fluid<=300;assert read()==before
 page.locator('#performance-open').click();page.locator('#preview-quality').select_option('detail');page.locator('[aria-label="Chiudi prestazioni"]').click();page.wait_for_timeout(700);detail=page.locator('#art').evaluate('(c)=>Math.max(c.width,c.height)');assert detail>=fluid;assert read()==before;assert page.evaluate('localStorage.getItem("prisma-preview-quality")')=='detail'
 page.reload(wait_until='networkidle');page.locator('#performance-open').click();assert page.locator('#preview-quality').input_value()=='detail';assert read()==before;page.screenshot(path=str(out/'prestazioni-desktop.png'));page.locator('[aria-label="Chiudi prestazioni"]').click();page.set_viewport_size({'width':390,'height':844});assert page.evaluate('document.documentElement.scrollWidth<=innerWidth');page.locator('#performance-open').click();assert page.locator('#preview-quality').is_visible();assert page.locator('#performance-dialog').bounding_box()['width']<=390;page.screenshot(path=str(out/'prestazioni-mobile.png'));assert not errors,errors;b.close();print(json.dumps({'fluidPixels':fluid,'detailPixels':detail}));print('GPU panel, quality modes, state preservation, persisted preferences and mobile layout: PASS',flush=True)
