from playwright.sync_api import sync_playwright
from pathlib import Path
import json
out=Path('/workspace/prisma-performance-audit')
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox','--use-angle=gl-egl','--ignore-gpu-blocklist','--disable-gpu-sandbox'])
 page=b.new_page();page.set_default_timeout(240000);page.goto('http://127.0.0.1:4173/',wait_until='commit');page.goto('about:blank');page.route('**/test-host',lambda r:r.fulfill(body='<html></html>',content_type='text/html'));page.goto('http://127.0.0.1:4173/test-host')
 result=page.evaluate('''async source=>{const old=await import(URL.createObjectURL(new Blob([source],{type:'text/javascript'}))),cur=await import('/renderer.js'),{preset}=await import('/model.js'),{newCreation,material}=await import('/creative-model.js');const a=new old.Renderer(document.createElement('canvas')),b=new cur.Renderer(document.createElement('canvas'));let comparisons=[];for(let i=0;i<6;i++){const s=preset(i);a.draw(s,.2,96,96);b.draw(s,.2,96,96,{preview:true});const x=a.pixels(),y=b.pixels();comparisons.push({preset:i,difference:x.reduce((n,v,k)=>n+(v!==y[k]),0)});}const s=newCreation();material(s,14);a.draw(s,.3,96,96);b.draw(s,.3,96,96,{preview:true});const x=a.pixels(),y=b.pixels();comparisons.push({preset:'modern',difference:x.reduce((n,v,k)=>n+(v!==y[k]),0)});for(let i=0;i<5;i++)b.draw(s,.3,64,64,{preview:true});b.pixels();b.pollGpuTime();const info=b.hardwareInfo();const attrs=b.gl.getContextAttributes(),error=b.gl.getError(),timing=b.gpuMilliseconds;await b.drawAccumulated(s,.3,80,80,{samples:2});const accumulated=b.pixels().some(v=>v!==0);a.dispose();b.dispose();return{comparisons,info,attrs,error,timing,accumulated};}''',(out/'renderer-before.js').read_text())
 assert all(q['difference']==0 for q in result['comparisons']),result;assert result['error']==0,result;assert result['accumulated'];assert result['attrs']['powerPreference']=='high-performance',result;assert not '\nimport ' in (out.parent/'prisma-studio/dist/renderer.js').read_text();(out/'render-metrics.json').write_text(json.dumps(result,indent=2));b.close();print(json.dumps(result));print('Actual WebGL: all six existing presets + modern material unchanged, GPU request, timing and accumulation: PASS',flush=True)
