from pathlib import Path
from playwright.sync_api import sync_playwright
from PIL import Image
import json,subprocess
out=Path('/workspace/prisma-organic-audit')
state=json.loads(subprocess.check_output(['node','--input-type=module','-e',"import {newCreation,sculpt} from './dist/creative-model.js';import {MATERIAL_STYLES} from './dist/studio-model.js';const s=sculpt(newCreation(),3);Object.assign(s,MATERIAL_STYLES[14].values,{petalBlend:0,petalRoot:0,petalRandom:0,petalCurl:0,scale:.73,palette:['#408bbe']});console.log(JSON.stringify(s));"],cwd='/workspace/prisma-studio'))
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox','--use-angle=gl-egl','--ignore-gpu-blocklist','--disable-gpu-sandbox']);page=b.new_page(viewport={'width':1120,'height':800},accept_downloads=True);page.set_default_timeout(180000);errors=[];page.on('pageerror',lambda e:errors.append(str(e)));page.add_init_script('window.testTools={};Object.defineProperty(document,"modelContext",{value:{registerTool(t){testTools[t.name]=t}}});');page.add_init_script("if(!localStorage.getItem('organic-test-started')){localStorage.setItem('prisma-current-v2',"+json.dumps(json.dumps({'state':state,'ratio':1,'phase':0}))+ ");localStorage.setItem('organic-test-started','1');}");page.goto('http://127.0.0.1:4173/',wait_until='networkidle');read=lambda:page.evaluate('testTools.read_creation.execute()');assert read()['petalBlend']==0
 page.locator('[data-tab=shape]').click();page.locator('summary',has_text='Radici e crescita organica').click();before=read();page.locator('#organic-spines').click();s=read();assert s['petalBlend']>=.78 and s['petalRoot']>=.55 and s['petalRandom']>=.22;assert all(s[k]==before[k] for k in ['palette','materialName','lights','petalSharp','petalCount','petalLength']);assert s['petalCurl']>.1;page.locator('[data-number=petalBlend]').fill('0.65');page.locator('[data-number=petalBlend]').dispatch_event('change');page.locator('[data-number=petalRoot]').fill('0.7');page.locator('[data-number=petalRoot]').dispatch_event('change');page.locator('[data-number=petalRandom]').fill('0.45');page.locator('[data-number=petalRandom]').dispatch_event('change');chosen=read();assert chosen['petalBlend']==.65 and chosen['petalRoot']==.7 and chosen['petalRandom']==.45;page.screenshot(path=str(out/'editor-organico.png'));page.locator('#perfect-sphere').click();assert read()['petalBlend']==0 and read()['petalAmount']==0;page.locator('#undo').click();assert read()==chosen;print('Existing shape → organic roots, sliders, pointed tips, sphere reset and undo: PASS',flush=True)
 page.locator('#favorite').click();page.wait_for_function('JSON.parse(localStorage.getItem("prisma-favorites-v2")||"[]").length===1');page.locator('#gallery-open').click()
 with page.expect_download() as dl:page.locator('#project-download').click()
 project=out/'radici-progetto.json';dl.value.save_as(str(project));assert json.loads(project.read_text())['state']==chosen;page.locator('#gallery-dialog button[aria-label="Chiudi galleria"]').click();page.locator('#reset').click();page.locator('#gallery-open').click();page.locator('[data-favorite-id]').click();assert read()==chosen;page.wait_for_timeout(600);page.reload(wait_until='networkidle');assert read()==chosen;print('Favorite, project JSON and reload preserve organic growth: PASS',flush=True)
 page.locator('#random-settings').click();page.locator('[data-lock=shape]').click();page.locator('#random-dialog button[aria-label=Chiudi]').click();page.locator('#similar').click();page.wait_for_function('document.querySelectorAll("[data-variant]").length===8 && !document.querySelector("#similar-again").disabled');page.locator('[data-variant="2"]').click();s=read();assert all(s[k]==chosen[k] for k in ['seed','petalBlend','petalRoot','petalRandom','petalCurl','petalSharp','petalCount','petalLength']);print('Shape lock preserves seeded organic geometry in variants: PASS',flush=True)
 page.set_viewport_size({'width':390,'height':844});assert page.evaluate('document.documentElement.scrollWidth<=innerWidth');page.set_viewport_size({'width':1120,'height':800});page.locator('#export-open').click();page.locator('#export-width').fill('192');page.locator('#export-width').dispatch_event('change');page.locator('#export-height').fill('192');page.locator('#export-height').dispatch_event('change');page.locator('#file-format').select_option('png')
 with page.expect_download(timeout=240000) as dl:page.locator('#download').click()
 dl.value.save_as(str(out/'radici-export.png'));page.wait_for_function('!document.querySelector("#download").disabled');assert Image.open(out/'radici-export.png').size==(192,192);print('Organic PNG export · 16 accumulated samples: PASS',flush=True)
 page.locator('[data-export=wallpaper]').click()
 with page.expect_download() as dl:page.locator('#download').click()
 html=out/'radici-wallpaper.html';dl.value.save_as(str(html));page.wait_for_function('!document.querySelector("#download").disabled');off=b.new_page(viewport={'width':320,'height':240});off.set_default_timeout(180000);requests=[];off.on('request',lambda q:requests.append(q.url));off.on('pageerror',lambda e:errors.append(str(e)));off.set_content(html.read_text());off.wait_for_function('document.querySelector("#art").width>=64');assert not requests and not errors,(requests,errors);assert off.locator('#art').evaluate('(c)=>!c.getContext("webgl2").isContextLost()&&c.getContext("webgl2").getError()===0');off.close();assert not errors,errors;b.close();print('Self-contained offline renderer with organic geometry: PASS',flush=True)
