from pathlib import Path
from playwright.sync_api import sync_playwright
from PIL import Image,ImageDraw,ImageFont
import json,io,base64
out=Path('/workspace/prisma-organic-audit')
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox','--use-angle=gl-egl','--ignore-gpu-blocklist','--disable-gpu-sandbox']);page=b.new_page();page.set_default_timeout(240000);page.on('console',lambda m:print(m.text,flush=True) if m.type=='log' else None);page.goto('http://127.0.0.1:4173/renderer.js')
 data=page.evaluate('''async oldSource=>{
 const {Renderer,fieldAt,sampleFrame}=await import('./renderer.js'),{newCreation,sculpt,normalizeCreation}=await import('./creative-model.js'),{MATERIAL_STYLES}=await import('./studio-model.js');const Old=await import(URL.createObjectURL(new Blob([oldSource],{type:'text/javascript'}))),r=new Renderer(document.createElement('canvas')),o=new Old.Renderer(document.createElement('canvas')),images=[],metrics={compat:[],fields:[],loops:[],controls:[]};const diff=(a,b)=>a.reduce((n,v,i)=>n+Math.abs(v-b[i]),0);
 const render=(s,rr=r,phase=0,size=192)=>{rr.draw(s,phase,size,size,{preview:true});const pixels=rr.pixels();if(rr.gl.getError())throw Error('GL');return pixels;};
 for(const i of [1,2,3]){const q=sculpt(newCreation(),i);Object.assign(q,MATERIAL_STYLES[11].values,{scale:.73,palette:['#949dae'],petalRandom:0,petalCurl:0});const old={...q,petalBlend:0,petalRoot:0,petalRandom:0};render(old,o);images.push({name:['','Riccio · prima','Borchie · prima','Aghi · prima'][i],url:o.canvas.toDataURL()});render(q);images.push({name:['','Riccio · radici fuse','Borchie · radici fuse','Aghi · radici fuse'][i],url:r.canvas.toDataURL()});metrics.compat.push({i,difference:diff(render(old),render(old,o))});console.log('Before/after '+i);}
 const q=sculpt(newCreation(),1);Object.assign(q,MATERIAL_STYLES[18].values,{palette:['#d74981','#843859','#24515c'],scale:.75,petalCurl:.58,petalRandom:.55});render(q);images.push({name:'Crescita curva e irregolare',url:r.canvas.toDataURL()});const a=render(q,r,0,96);q.petalRandom=0;metrics.controls.push({control:'irregularity',difference:diff(a,render(q,r,0,96))});q.petalBlend=0;q.petalRoot=0;metrics.controls.push({control:'roots',difference:diff(a,render(q,r,0,96))});
 q.petalRandom=.55;q.petalBlend=.78;q.petalRoot=.55;q.motions.petalPhase={enabled:true,mode:'cycle',cycles:1,direction:1,phase:0};q.motions.petalCurl={enabled:true,mode:'wave',cycles:1,direction:1,phase:0,amplitude:.18};metrics.loops.push({difference:diff(render(q,r,0,96),render(q,r,Math.PI*2,96)),moving:diff(render(q,r,0,96),render(q,r,Math.PI/2,96))});const restored=normalizeCreation(q);metrics.restore=['petalBlend','petalRoot','petalRandom','petalCurl'].every(k=>restored[k]===q[k]);
 let source=await (await fetch('./renderer.js')).text();source=source.replace('const RESOLVE=',`MODERN_FRAG=shaderFunction(MODERN_FRAG,'main','void main(){vec2 uv=(gl_FragCoord.xy-.5*uResolution)/min(uResolution.x,uResolution.y)*3.4;fragColor=vec4(vec3(field(vec3(uv,uRuntime.z))<0.?1.:0.),1.);}');\nconst RESOLVE=`).replace('options.normalDiagnostic?2:+!!options.diagnostic','options.fieldPlane||0');const D=await import(URL.createObjectURL(new Blob([source],{type:'text/javascript'}))),d=new D.Renderer(document.createElement('canvas'));
 for(const i of [1,2,3]){const s=sculpt(newCreation(),i);Object.assign(s,{petalRandom:.65,petalCurl:.6,rotateZ:11,asymmetry:.1,twist:.15,scale:.75});for(const plane of [0,.23]){d.draw(s,0,64,64,{fieldPlane:plane});const pixels=d.pixels();let mismatch=0,boundary=0;for(let y=0;y<64;y++)for(let x=0;x<64;x++){const v=fieldAt(s,[(x+.5-32)/64*3.4,(32-y-.5)/64*3.4,plane]),inside=pixels[(y*64+x)*4]>127;if(inside!==(v<0)){mismatch++;if(Math.abs(v)<.0005)boundary++;}}metrics.fields.push({i,plane,mismatch,boundary});}}
 for(const m of [0,2,18]){const s=sculpt(newCreation(),2);Object.assign(s,MATERIAL_STYLES[m].values,{palette:['#6598db','#e87ba8'],scale:.85});const p=render(s,r,0,64);let lit=0;for(let i=0;i<p.length;i+=4)if(p[i]+p[i+1]+p[i+2]>15)lit++;metrics.controls.push({material:m,visible:lit});}
 const bench=sculpt(newCreation(),3);Object.assign(bench,MATERIAL_STYLES[14].values);render(bench,r,0,64);metrics.benchmark=[];for(let i=0;i<3;i++){const t=performance.now();render(bench,r,i*.1,256);metrics.benchmark.push(Math.round(performance.now()-t));}
 d.dispose();r.dispose();o.dispose();return {images,metrics};}''',(out/'renderer-before.js').read_text())
 print(json.dumps(data['metrics']),flush=True);(out/'metrics.json').write_text(json.dumps(data['metrics'],indent=2));font=ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',14);sheet=Image.new('RGB',(448,912),'#181a20');draw=ImageDraw.Draw(sheet)
 for j,item in enumerate(data['images']):x=16+j%2*216;y=16+j//2*224;draw.text((x,y),item['name'],font=font,fill='white');sheet.paste(Image.open(io.BytesIO(base64.b64decode(item['url'].split(',')[1]))).convert('RGB'),(x,y+24))
 sheet.save(out/'confronto-radici.png');assert all(v['difference']==0 for v in data['metrics']['compat']),data['metrics']['compat'];assert all(v['mismatch']<=v['boundary']+3 for v in data['metrics']['fields']),data['metrics']['fields'];assert data['metrics']['restore'];assert all(v['difference']==0 and v['moving']>1000 for v in data['metrics']['loops']);assert all(v.get('difference',10000)>1000 for v in data['metrics']['controls']);b.close();print('ORGANIC ROOTS, COMPATIBILITY, MATERIALS, FIELDS, SEED AND LOOPS: PASS',flush=True)
