from pathlib import Path
from playwright.sync_api import sync_playwright
from PIL import Image
import json
out=Path('/workspace/prisma-petals-audit')
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox','--use-angle=gl-egl','--ignore-gpu-blocklist','--disable-gpu-sandbox']);page=b.new_page(viewport={'width':1280,'height':900},accept_downloads=True);page.set_default_timeout(180000);errors=[];page.on('pageerror',lambda e:errors.append(str(e)));page.add_init_script('window.testTools={};Object.defineProperty(document,"modelContext",{value:{registerTool(t){testTools[t.name]=t}}});');page.goto('http://127.0.0.1:4173/',wait_until='networkidle');page.wait_for_function('document.querySelector("#art").width>200');state=lambda:page.evaluate('testTools.read_creation.execute()')
 def tab(name):page.locator('[data-tab='+name+']').click()
 def stop():
  if page.locator('#play').get_attribute('aria-label')=='Metti in pausa':page.locator('#play').click()
 def value(k,v):
  el=page.locator('[data-number="'+k+'"]');el.fill(str(v));el.dispatch_event('input');el.dispatch_event('change')
 def details(name):
  el=page.locator('summary',has_text=name)
  if not el.locator('..').evaluate('(e)=>e.open'):el.click()
 tab('shape');page.locator('#load-bloom-example').click();stop();s=state();assert s['materialName']=='Silicone satinato' and s['stemAmount']>.5 and s['colorWaveAmount']==1;assert s['motions']['petalOpen']['enabled'] and s['motions']['colorWavePhase']['enabled'];page.locator('#timeline').fill('100');page.screenshot(path=str(out/'bloom-editor.png'));palette=s['palette'];material=s['materialName'];page.locator('[data-sculpt="3"]').click();s=state();assert s['petalSharp']==1 and s['petalCoverage']==1 and s['palette']==palette and s['materialName']==material and s['stemAmount']==0;assert not s['motions']['petalOpen']['enabled'];value('petalSharp',.45);assert state()['petalSharp']==.45;page.locator('#perfect-sphere').click();s=state();assert s['petalAmount']==0 and s['stemAmount']==0 and s['volume']==1 and s['palette']==palette
 page.locator('[data-sculpt="0"]').click();tab('color');value('colorWaveAmount',1);details('Direzioni, vortici e sfumature');value('colorWaveRadius',.9);assert state()['colorWaveRadius']==.9;tab('motion');page.locator('[data-motion-preset=bloom]').click();stop();page.locator('[data-motion-preset=chromatic]').click();stop();s=state();assert s['motions']['petalOpen']['enabled'] and s['motions']['colorWavePhase']['enabled'];details('Petali e gambo');details('Petali / punte');page.locator('[data-path-check="motions.petalSharp.enabled"]').check();assert state()['motions']['petalSharp']['enabled'];print('Bloom, needle examples, independent controls, perfect sphere and combined motion: PASS',flush=True)
 tab('light');before=state();page.locator('[data-light-source="0"]').click();page.locator('[data-light-source="1"]').click();s=state();assert len(s['lights'])==len(before['lights'])+2 and s['lights'][-2]['type']=='bar' and s['lights'][-1]['type']=='ring';details('Schemi di illuminazione');page.locator('#light-rig').select_option('3');s=state();assert len(s['lights'])==3 and all(l['type']=='ring' for l in s['lights']);assert s['palette']==before['palette'] and s['petalAmount']==before['petalAmount'];page.locator('[data-light-depth=back]').click();assert state()['lights'][0]['z']<0;page.screenshot(path=str(out/'luci-editor.png'));print('Add neon and halogen sources, editable 3D depth, replace lighting rig only: PASS',flush=True)
 # Test shape locks including the new controls and rotations; zero intensity is exact.
 page.locator('#random-settings').click();page.locator('[data-lock=shape]').click();page.locator('#random-dialog button[aria-label=Chiudi]').click();before=state();page.locator('#similar').click();page.wait_for_function('document.querySelectorAll("[data-variant]").length===8');page.locator('#similar-intensity').fill('100');page.locator('#similar-intensity').dispatch_event('change');page.wait_for_function('document.querySelectorAll("[data-variant]").length===8 && !document.querySelector("#similar-again").disabled');page.screenshot(path=str(out/'varianti-editor.png'));page.locator('[data-variant="4"]').click();s=state();assert all(s[k]==before[k] for k in ['rotateX','rotateY','petalAmount','petalOpen','petalSharp','petalCount','stemAmount']);assert s['palette']!=before['palette'];page.locator('#similar').click();page.locator('#similar-intensity').fill('0');page.locator('#similar-intensity').dispatch_event('change');page.wait_for_function('document.querySelectorAll("[data-variant]").length===8 && !document.querySelector("#similar-again").disabled');before=state();page.locator('[data-variant="2"]').click();assert state()==before;print('8 stronger variants, intensity regeneration, exact 0%, shape locks: PASS',flush=True)
 # Preserve an animated Bloom, including new tracks, through favorite and JSON round trips.
 tab('shape');page.locator('#load-bloom-example').click();stop();chosen=state();page.locator('#favorite').click();page.wait_for_function('JSON.parse(localStorage.getItem("prisma-favorites-v2")||"[]").length===1');page.locator('#gallery-open').click()
 with page.expect_download() as dl:page.locator('#project-download').click()
 project=out/'bloom-progetto.json';dl.value.save_as(str(project));assert json.loads(project.read_text())['state']==chosen;page.locator('#gallery-dialog button[aria-label="Chiudi galleria"]').click();page.locator('#reset').click();page.locator('#gallery-open').click();page.locator('[data-favorite-id]').click();assert state()==chosen;page.wait_for_timeout(600);page.reload(wait_until='networkidle');assert state()==chosen;page.locator('#gallery-open').click();page.locator('#project-file').set_input_files(str(project));page.wait_for_function('!document.querySelector("#gallery-dialog").open');assert state()==chosen;print('Favorites, JSON import/export, reload preserve all geometry and animation: PASS',flush=True)
 tab('background');details('Ombra e caustica');value('grounding',1);value('groundShadow',.7);value('groundCaustic',0);s=state();assert s['grounding']==1 and s['groundShadow']==.7 and s['groundCaustic']==0;value('grounding',0);page.set_viewport_size({'width':390,'height':844});page.wait_for_timeout(500);assert page.evaluate('document.documentElement.scrollWidth<=innerWidth');page.screenshot(path=str(out/'mobile-editor.png'));page.set_viewport_size({'width':1280,'height':900});page.locator('#export-open').click()
 def size(w,h):
  page.locator('#export-width').fill(str(w));page.locator('#export-width').dispatch_event('change');page.locator('#export-height').fill(str(h));page.locator('#export-height').dispatch_event('change')
 size(512,512);page.locator('#file-format').select_option('png')
 with page.expect_download(timeout=240000) as dl:page.locator('#download').click()
 dl.value.save_as(str(out/'bloom-512.png'));page.wait_for_function('!document.querySelector("#download").disabled');assert Image.open(out/'bloom-512.png').size==(512,512);print('Actual Bloom PNG export, 16 accumulated samples: PASS',flush=True)
 page.locator('[data-export=wallpaper]').click()
 with page.expect_download() as dl:page.locator('#download').click()
 html=out/'bloom-wallpaper.html';dl.value.save_as(str(html));page.wait_for_function('!document.querySelector("#download").disabled');off=b.new_page(viewport={'width':240,'height':240});requests=[];off.on('request',lambda r:requests.append(r.url));off.on('pageerror',lambda e:errors.append(str(e)));off.set_content(html.read_text());off.wait_for_function('document.querySelector("#art").width>100');assert not requests;assert off.locator('#art').evaluate('(c)=>!c.getContext("webgl2").isContextLost()&&c.getContext("webgl2").getError()===0');off.close();print('Self-contained offline animated Bloom HTML: PASS',flush=True)
 page.locator('[data-export=video]').click();page.locator('#video-target').select_option('iphone');size(96,160);page.locator('#video-fps').select_option('60')
 with page.expect_download(timeout=300000) as dl:page.locator('#download').click()
 dl.value.save_as(str(out/'bloom-loop-60fps.mp4'));page.wait_for_function('!document.querySelector("#download").disabled');page.locator('#export-close').click();assert not errors,errors;print('Real 60 fps Bloom MP4, full loop: PASS',flush=True);b.close()
