from pathlib import Path
from playwright.sync_api import sync_playwright
from PIL import Image,ImageDraw,ImageFont
import base64,io,json
out=Path('/workspace/prisma-petals-audit')
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox','--use-angle=gl-egl','--ignore-gpu-blocklist','--disable-gpu-sandbox']);page=b.new_page();page.goto('http://127.0.0.1:4173/renderer.js');data=page.evaluate('''async()=>{const {Renderer}=await import('./renderer.js'),{newCreation,sculpt,bloomExample}=await import('./creative-model.js'),{MATERIAL_STYLES}=await import('./studio-model.js');const r=new Renderer(document.createElement('canvas')),morphs=[],images=[];for(const coverage of [0,.25,.5,.75,1]){const s=sculpt(newCreation(),0);Object.assign(s,MATERIAL_STYLES[14].values,{petalCoverage:coverage,petalSharp:coverage,scale:.65,palette:['#61a9fc']});r.draw(s,0,96,96,{preview:true});const a=r.pixels();let visible=0;for(let i=0;i<a.length;i+=4)if(a[i]+a[i+1]+a[i+2]>30)visible++;morphs.push({coverage,visible});}const s=bloomExample();for(const phase of [0,Math.PI/2,Math.PI]){await r.drawAccumulated(s,phase,256,256,{samples:4});images.push(r.canvas.toDataURL());}const error=r.gl.getError();r.dispose();return {morphs,images,error};}''');assert data['error']==0 and all(q['visible']>100 for q in data['morphs']),data['morphs'];font=ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',16);sheet=Image.new('RGB',(832,316),'#181a20');d=ImageDraw.Draw(sheet)
 for i,url in enumerate(data['images']):x=16+i*272;d.text((x,16),'Bloom · fase '+str(i+1),font=font,fill='white');sheet.paste(Image.open(io.BytesIO(base64.b64decode(url.split(',')[1]))).convert('RGB'),(x,44))
 sheet.save(out/'bloom-onde-cromatiche.png');(out/'intermediates.json').write_text(json.dumps(data['morphs'],indent=2));b.close();print('Continuous flower-to-hedgehog intermediates and final Bloom example: PASS '+json.dumps(data['morphs']),flush=True)
