import assert from 'node:assert/strict';
import {newCreation,sculpt} from '../prisma-studio/dist/creative-model.js';
import {interpretDescription,applyDescriptionPlan,descriptionCatalog} from '../prisma-studio/dist/description.js';
import {GROUPS} from '../prisma-studio/dist/model.js';
const base=sculpt(newCreation(),4);Object.assign(base,{deform:.17,petalDisorder:.4,textureWrinkles:0,textureFolds:0,textureWear:0,textureRipples:0});
const shape=s=>Object.fromEntries(GROUPS.shape.map(k=>[k,s[k]]));
const run=(text,s=base)=>{const plan=interpretDescription(text,s),result=applyDescriptionPlan(s,plan);console.log(JSON.stringify({text,operations:plan.operations,unrecognized:plan.unrecognized}));assert.deepEqual(plan.unrecognized,[]);return result.state;};
let s=run('Superficie con grinze e pieghe, più irregolare');assert(s.textureWrinkles>0);assert(s.textureFolds>0);assert(s.textureOrganic>base.textureOrganic);assert.deepEqual(shape(s),shape(base));assert.equal(s.materialName,base.materialName);
s=run('Metallo abraso');assert.equal(s.materialName,'Metallo liquido');assert(s.textureWear>0);assert.deepEqual(shape(s),shape(base));
s=run('Increspature della superficie più fini');assert(s.textureRipples>0);assert(s.textureScale>base.textureScale);assert.equal(s.waves,base.waves);assert.deepEqual(shape(s),shape(base));
s=run('Texture più organica');assert(s.textureOrganic>base.textureOrganic);assert.deepEqual(shape(s),shape(base));
s=run('Texture più regolare');assert(s.textureOrganic<base.textureOrganic);assert.deepEqual(shape(s),shape(base));
s=run('Rilievo superficie 80%, scala trama 2.5, grinze 40%, pieghe 15%, abrasioni 25%, increspature della superficie 65%');assert.equal(s.textureDepth,.8);assert.equal(s.textureScale,2.5);assert.equal(s.textureWrinkles,.4);assert.equal(s.textureFolds,.15);assert.equal(s.textureWear,.25);assert.equal(s.textureRipples,.65);assert.deepEqual(shape(s),shape(base));
let dirty={...base,textureWrinkles:.8,textureFolds:.4,textureWear:.9,textureRipples:.5,surfaceTexture:.8};s=run('Togli texture',dirty);for(const key of ['textureWrinkles','textureFolds','textureWear','textureRipples','surfaceTexture'])assert.equal(s[key],0);assert.deepEqual(shape(s),shape(dirty));assert.equal(s.materialName,dirty.materialName);assert.equal(s.metal,dirty.metal);
s=run('Togli texture dal metallo',dirty);assert.equal(s.metal,dirty.metal);assert.equal(s.surfaceTexture,0);
s=run('Texture senza pieghe',dirty);assert.equal(s.textureFolds,0);assert.equal(s.textureWrinkles,dirty.textureWrinkles);assert.equal(s.textureWear,dirty.textureWear);
s=run('Grinze sulle radici');assert(s.textureWrinkles>0);assert.deepEqual(shape(s),shape(base));
s=run('Radici più irregolari');assert(s.petalDisorder>base.petalDisorder);assert.equal(s.textureOrganic,base.textureOrganic);
s=run('Petali più piegati');assert(s.petalCurl>base.petalCurl);assert.equal(s.textureFolds,0);
s=run('Increspature 50%');assert.equal(s.waves,.2);assert.equal(s.textureRipples,0);
s=run('Texture con graffi e usura');assert(s.textureWear>0);assert.deepEqual(shape(s),shape(base));
s=run('Superficie della sfera più organica');assert(s.textureOrganic>base.textureOrganic);assert.deepEqual(shape(s),shape(base));
s=run('Texture più fine e meno profonda');assert(s.textureScale>base.textureScale);assert(s.textureDepth<base.textureDepth);assert.deepEqual(shape(s),shape(base));
for(let index=0;index<4;index++){s=applyDescriptionPlan(base,{operations:[{type:'textureStyle',index}]}).state;assert.deepEqual(shape(s),shape(base));assert.equal(s.materialName,base.materialName);assert.equal(s.metal,base.metal);assert.equal(s.transparency,base.transparency);}
assert.throws(()=>applyDescriptionPlan(base,{operations:[{type:'set',key:'textureDepth',value:.8},{type:'textureStyle',index:4}]}));assert.throws(()=>applyDescriptionPlan(base,{operations:[{type:'textureStyle',index:'0'}]}));assert.equal(base.textureDepth,.35);
const partial=interpretDescription('Superficie con grinze e piume',base);assert(partial.operations.some(o=>o.key==='textureWrinkles'));assert(partial.unrecognized.some(t=>t.includes('piume')));assert.equal(descriptionCatalog().textureStyles.length,4);
console.log('Texture combinations, scope isolation, additive relative edits, removal, presets, atomic validation and unknown fragments: PASS');
s=run('Regolarità della texture 80%');assert(Math.abs(s.textureOrganic-.2)<1e-12);assert.deepEqual(shape(s),shape(base));
s=run('Irregikarita della texture 90%');assert.equal(s.textureOrganic,.9);assert.deepEqual(shape(s),shape(base));
s=run('Texture in amniera più regolare');assert(s.textureOrganic<base.textureOrganic);assert.deepEqual(shape(s),shape(base));
s=run('Materia con increspature 40%');assert.equal(s.textureRipples,.4);assert.equal(s.waves,base.waves);assert.deepEqual(shape(s),shape(base));
s=run('Texture irregolarità 85% direzione 45 gradi');assert.equal(s.textureOrganic,.85);assert.equal(s.textureAngle,45);assert.deepEqual(shape(s),shape(base));
s=run('Texture regolarità 100%');assert.equal(s.textureOrganic,0);assert.deepEqual(shape(s),shape(base));
s=run('Grinze morbide');assert(s.textureWrinkles>0);assert(s.textureDepth<base.textureDepth);assert.deepEqual(shape(s),shape(base));
console.log('Inverse regularity, actual user typos, material scope and scoped numeric aliases: PASS');
